{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Dim Client\",\"Dim Currency\",\"Dim Aging Buckets\",\"Dim Timesheet\",\"Dim Employee\",\"Dim Proforma\",\"Dim Role Type\",\"Dim Matter\",\"Dim Invoice\",\"Dim Date\",\"Dim Receipts\",\"Dim Office\",\"Dim Practice Group\",\"Dim Firm Target\",\"Fact WIP Snapshot\",\"Fact Matter Snapshot\",\"Fact Invoice Transactions\",\"Fact Employment By Date\",\"Fact Proforma Transactions\",\"Fact Timesheet\",\"Fact AR Snapshot\",\"Fact Firm Target Snapshot\",\"Fact Receipt Transactions\",\"Bridge Matter Roles\",\"Number Type\",\"Timeframe Selection\",\"DatabricksHTTPPath\",\"DatabricksHost\",\"Trend Arrows\",\"Catalog\",\"Reporting Preferences\",\"Fact Employee Photo\",\"fn_RollingMonthSort\",\"Fact Employee Snapshot\",\"Leaderboard Selection\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.1066.0 (23.10)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DatabricksHost",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Enter the Databricks Host provided by Entegrata. Example: adb-1111111111111111.00.azuredatabricks.net",
        "expression": "\"adb-165701939868154.14.azuredatabricks.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a5f4da65-72ac-4d00-9c5f-69a1dc0877ba",
        "queryGroup": "Parameters"
      },
      {
        "name": "DatabricksHTTPPath",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Enter the HTTP Path provided by Entegrata. Example: sql/protocolv1/o/0000000000000000/1111-111111-abcd111",
        "expression": "\"/sql/1.0/warehouses/94f4945c0e58e998\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "fd3ef68a-a914-45b1-b989-349c9e778ff6",
        "queryGroup": "Parameters"
      },
      {
        "name": "Catalog",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dw_gold\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "77bd2048-03aa-49c6-aace-618f98b05dc3",
        "queryGroup": "Parameters"
      },
      {
        "name": "fn_RollingMonthSort",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(MonthNum as number) =>",
          "let",
          "     TodayMonth = Date.Month(Date.From(DateTime.LocalNow())), ",
          "    MonthDiff = TodayMonth - 1,",
          "    MonthTop = 12 - TodayMonth + 1,",
          "    output = if MonthNum >= TodayMonth then -1 * (MonthNum - MonthDiff) else -1 * (MonthNum + MonthTop)",
          "   ",
          "in",
          "     output"
        ],
        "kind": "m",
        "lineageTag": "95aa823f-c5c3-4e02-b895-081b9c2d7812",
        "queryGroup": "Functions"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "PBI Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Functions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Databricks Tables"
      }
    ],
    "relationships": [
      {
        "name": "39c4aa56-fd5b-4bf9-b44d-aebeb578a75a",
        "fromColumn": "Client Key",
        "fromTable": "Fact Invoice Transactions",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "96a5a626-90c6-4b6b-84fb-8cb61af93ee4",
        "fromColumn": "Client Key",
        "fromTable": "Fact Matter Snapshot",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "1193074a-f968-4849-8688-23d2e4e76f74",
        "fromColumn": "Client Key",
        "fromTable": "Fact Timesheet",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "83c7a3f2-9368-4a6a-b0d9-85f95efce06e",
        "fromColumn": "Client Key",
        "fromTable": "Fact Proforma Transactions",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "30b5f616-8311-4f12-9654-3db5abac20ca",
        "fromColumn": "Client Key",
        "fromTable": "Fact WIP Snapshot",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "9a811ee2-0b0e-40e9-a3c9-c29c5944af88",
        "fromColumn": "Client Key",
        "fromTable": "Fact AR Snapshot",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "0f305fa6-a800-4491-bfc7-78ad5a7d1fe4",
        "fromColumn": "Client Key",
        "fromTable": "Fact Receipt Transactions",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "96f98fea-ec7a-48aa-9e35-b4dfd8ce807e",
        "fromColumn": "Matter Key",
        "fromTable": "Fact Invoice Transactions",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "e4e7aeb2-9572-4825-abfc-a3698e3d53f1",
        "fromColumn": "Matter Key",
        "fromTable": "Fact Matter Snapshot",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "8c5d9f62-6623-46f6-8ba6-7e59650f2cde",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Matter Key",
        "fromTable": "Bridge Matter Roles",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "6489cb50-ee36-4d7c-80f0-52ae5ab458c3",
        "fromColumn": "Matter Key",
        "fromTable": "Fact Timesheet",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "0bf2245a-6086-418d-95ac-f12581b4bceb",
        "fromColumn": "Matter Key",
        "fromTable": "Fact WIP Snapshot",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "df0e42d6-51d6-4358-8474-ead5ed9661f1",
        "fromColumn": "Matter Key",
        "fromTable": "Fact AR Snapshot",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "899e2b96-5fbf-4335-90db-f50577564e7d",
        "fromColumn": "Matter Key",
        "fromTable": "Fact Receipt Transactions",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "d5efe76f-e371-47dc-9439-87263e492dc4",
        "fromColumn": "Role Type Key",
        "fromTable": "Bridge Matter Roles",
        "toColumn": "Role Type Key",
        "toTable": "Dim Role Type"
      },
      {
        "name": "cb376bc9-3069-4298-bd9b-fbd35e374c49",
        "fromColumn": "Timesheet Key",
        "fromTable": "Dim Timesheet",
        "toColumn": "Timesheet Key",
        "toTable": "Fact Timesheet"
      },
      {
        "name": "f62aee8d-0721-4ced-a222-75c85ccc8685",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Invoice Transactions",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "41cd549a-a958-4352-b0ce-563704cd34cf",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Matter Snapshot",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "e18fe334-fd6e-4e5e-97d6-4aea9aa8d1c7",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Proforma Transactions",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "02658cff-5c83-4b8b-bd7d-b18e06e14f72",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact WIP Snapshot",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "f7a86bad-2d8e-4834-8747-be3e6d3fd579",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Employment By Date",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "138deaaa-d3e8-4f5d-8546-a467d2fa8579",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact AR Snapshot",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "318320eb-8023-41ca-8052-d387e99b98c3",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Receipt Transactions",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "dd4fec85-f0f2-4860-bed8-8603b6712a73",
        "fromColumn": "Office Key",
        "fromTable": "Fact Invoice Transactions",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "83f77e61-62ce-4f79-a3ac-2eec179b1943",
        "fromColumn": "Office Key",
        "fromTable": "Fact Matter Snapshot",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "a78f63e3-36db-47cc-ae2a-250d84bd7e85",
        "fromColumn": "Office Key",
        "fromTable": "Fact Timesheet",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "df15ad9a-508e-4c43-afc2-b3274a863299",
        "fromColumn": "Office Key",
        "fromTable": "Fact Proforma Transactions",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "4c382f18-74e6-482b-b191-d48592e079ea",
        "fromColumn": "Office Key",
        "fromTable": "Fact WIP Snapshot",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "a63ea13a-6b87-4a01-a3b2-10e91f5fac0e",
        "fromColumn": "Office Key",
        "fromTable": "Fact Employment By Date",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "0aa30c8c-3cda-4572-8dca-ea57e65a2cfa",
        "fromColumn": "Office Key",
        "fromTable": "Fact AR Snapshot",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "08996341-8d70-43dc-9241-c54ddabbe58e",
        "fromColumn": "Office Key",
        "fromTable": "Fact Receipt Transactions",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "41eaeccd-52f7-48a8-be66-b997dfa9ee38",
        "fromColumn": "Invoice Key",
        "fromTable": "Dim Invoice",
        "toColumn": "Invoice Key",
        "toTable": "Fact Invoice Transactions"
      },
      {
        "name": "1eff9af2-a7d2-43b6-9eee-223b954b5718",
        "fromColumn": "Aging Buckets Key",
        "fromTable": "Fact AR Snapshot",
        "toColumn": "Aging Buckets Key",
        "toTable": "Dim Aging Buckets"
      },
      {
        "name": "0343d0ec-24e5-42af-8df7-9bcb0cf7ce0d",
        "fromColumn": "Receipts Key",
        "fromTable": "Fact Receipt Transactions",
        "toColumn": "Receipts Key",
        "toTable": "Dim Receipts"
      },
      {
        "name": "d99aec0d-b6de-4c1b-8a31-30b8ce3f7d8c",
        "fromColumn": "Matter Key",
        "fromTable": "Fact Proforma Transactions",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "1849a3bf-7256-49a0-9514-e5cb5154b2e1",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Timesheet",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "16bebcef-c68c-4464-83ff-a7cea6043529",
        "fromColumn": "Employee Key",
        "fromTable": "Bridge Matter Roles",
        "toColumn": "Employee Key",
        "toTable": "Dim Employee"
      },
      {
        "name": "a2c75de6-dae9-46ea-8d17-8168d2256217",
        "fromColumn": "Firm Target Key",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "Firm Target Key",
        "toTable": "Dim Firm Target"
      },
      {
        "name": "6fda592c-5ad8-4a5a-b92f-07974bce9966",
        "fromColumn": "Target Date",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "f37ff565-10d9-4d91-b347-320ebf99a1c9",
        "fromColumn": "Target Currency Key",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "Currency Key",
        "toTable": "Dim Currency"
      },
      {
        "name": "770ea8d6-4bdb-4ade-8a9c-1bc3bec971cb",
        "fromColumn": "Client Key",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "Client Key",
        "toTable": "Dim Client"
      },
      {
        "name": "d8253388-329a-4980-8619-e6d9df0e6210",
        "fromColumn": "Matter Key",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "Matter Key",
        "toTable": "Dim Matter"
      },
      {
        "name": "02043e00-6824-4684-8fbc-4743e611dfa7",
        "fromColumn": "Office Key",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "ae3b8c49-a965-4f13-90e3-adb51e6fae81",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Firm Target Snapshot",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "10e39bf8-153b-43da-9051-ffbfc4d75d36",
        "fromColumn": "Invoice Create Date",
        "fromTable": "Fact Invoice Transactions",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "fa073547-5823-489a-b29b-9b76b23cc2fc",
        "fromColumn": "Time Worked Date",
        "fromTable": "Fact Timesheet",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "8a02ec8e-16b8-42d3-9672-95c0c66dda43",
        "fromColumn": "Proforma Date",
        "fromTable": "Fact Proforma Transactions",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "071a29d4-aad2-4ee3-add9-538d5f5697fa",
        "fromColumn": "As of Date",
        "fromTable": "Fact WIP Snapshot",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "598e86f7-7087-45ec-aec1-b1903c38b00c",
        "fromColumn": "As of Date",
        "fromTable": "Fact AR Snapshot",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "5c61e24c-ff44-427f-979f-0da667ccab19",
        "fromColumn": "As of Date",
        "fromTable": "Fact Employment By Date",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "24084f02-1d83-475e-843a-c621b1f80df4",
        "fromColumn": "Receipt Date",
        "fromTable": "Fact Receipt Transactions",
        "toColumn": "The Date",
        "toTable": "Dim Date"
      },
      {
        "name": "fae5f817-0b33-4d67-9a46-7af07db73617",
        "fromColumn": "Employee Key",
        "fromTable": "Fact Employment By Date",
        "toColumn": "Employee Key",
        "toTable": "Dim Employee"
      },
      {
        "name": "225c1947-96b2-4fb3-b18e-af94429d408f",
        "fromColumn": "Employee Key",
        "fromTable": "Fact Employee Photo",
        "toColumn": "Employee Key",
        "toTable": "Dim Employee"
      },
      {
        "name": "ec3d54d8-2b4e-4cc8-b337-044e182914c0",
        "fromColumn": "Employee Key",
        "fromTable": "Fact Employee Snapshot",
        "toColumn": "Employee Key",
        "toTable": "Dim Employee"
      },
      {
        "name": "d018e5c4-2e77-4a4a-8d8e-db3fa0ca0694",
        "fromColumn": "Practice Group Key",
        "fromTable": "Fact Employee Snapshot",
        "toColumn": "Practice Group Key",
        "toTable": "Dim Practice Group"
      },
      {
        "name": "8614017d-3a31-4c23-a70c-87cedb1dcefc",
        "fromColumn": "Office Key",
        "fromTable": "Fact Employee Snapshot",
        "toColumn": "Office Key",
        "toTable": "Dim Office"
      },
      {
        "name": "1e60bf31-b115-4e69-a8e4-3eb2ce4712a9",
        "fromColumn": "Aging Buckets Key",
        "fromTable": "Fact WIP Snapshot",
        "toColumn": "Aging Buckets Key",
        "toTable": "Dim Aging Buckets"
      },
      {
        "name": "5ae7d7a6-cc66-4d38-a3be-b2ab07972789",
        "fromColumn": "Proforma Key",
        "fromTable": "Fact Proforma Transactions",
        "toColumn": "Proforma Key",
        "toTable": "Dim Proforma"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Dim Client",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8edae444-757c-4b0e-be8d-bbc1675a0c95",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Website Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7d11db1-57f0-413d-b144-d4fa154066a7",
            "sourceColumn": "Website Text",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd0f6e21-e27c-4c46-9b50-d19c74a99f28",
            "sourceColumn": "Phone Number",
            "summarizeBy": "none"
          },
          {
            "name": "Country Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e6371ae-4be2-4a1b-a0ef-041a20911b56",
            "sourceColumn": "Country Description",
            "summarizeBy": "none"
          },
          {
            "name": "Country Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11d330be-b8c3-4b20-9e1f-3fc998bd8075",
            "sourceColumn": "Country Code",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14dfebbc-83d4-4fb4-a645-eeaf5e61fef0",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "State Province Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "272e9013-ea14-4b33-8f2c-8b6097d74da4",
            "sourceColumn": "State Province Description",
            "summarizeBy": "none"
          },
          {
            "name": "State Province Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2541572-4b8b-4b07-af01-6268d487dafa",
            "sourceColumn": "State Province Code",
            "summarizeBy": "none"
          },
          {
            "name": "Firm Area of Law Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02ebbda5-1eb3-4dce-b430-ede91be8acea",
            "sourceColumn": "Firm Area of Law Description",
            "summarizeBy": "none"
          },
          {
            "name": "Firm Industry Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4769e98-7058-4c94-b7de-00e90631375b",
            "sourceColumn": "Firm Industry Description",
            "summarizeBy": "none"
          },
          {
            "name": "Client Status Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16eaf7ac-1d0f-4519-b037-1d1dd98ac910",
            "sourceColumn": "Client Status Description",
            "summarizeBy": "none"
          },
          {
            "name": "Client Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5feb93f9-1fd1-4f82-a05c-b5615b0d7a5e",
            "sourceColumn": "Client Name",
            "summarizeBy": "none"
          },
          {
            "name": "Client Index I D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d42d751f-c05f-400e-91a6-07f9724f300c",
            "sourceColumn": "Client Index I D",
            "summarizeBy": "sum"
          },
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a1d0827-8e97-4f61-be79-4ec28dff7c0c",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccdf8561-fc20-475e-9de0-ac0ac103e1d3",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bed24b1-97aa-4f4a-a09c-90af002488e9",
            "sourceColumn": "Client Display Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9154b3ae-f780-474b-8552-88306441cef5",
        "partitions": [
          {
            "name": "Dim Client",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_client_Table = main_Schema{[Name=\"dim_client\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_client_Table,{\"ClientKey\", \"ClientID\", \"ClientIndexID\", \"ClientName\", \"ClientStatusDescription\", \"FirmIndustryDescription\", \"FirmAreaofLawDescription\", \"StateProvinceCode\", \"StateProvinceDescription\", \"PostalCode\", \"CountryCode\", \"CountryDescription\", \"PhoneNumber\", \"WebsiteText\", \"isCurrentRecordFlag\", \"ClientDisplayName\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{ {\"Firm Areaof Law Description\", \"Firm Area of Law Description\"}, {\"Client I D\", \"Client ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "The Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "65270417-cd1d-44f8-b70d-a37ee625fc89",
            "sourceColumn": "The Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cad4353d-94a0-4029-b046-c4b5039dca84",
            "sourceColumn": "Year Number",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "9a94694e-5a83-4d13-9690-e1eb38e84322",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none"
          },
          {
            "name": "End of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "25bd64dd-a614-4d6f-8391-68c86d1739ba",
            "sourceColumn": "End of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "640d435f-90f3-44fb-9341-c0f9da9da1fd",
            "sourceColumn": "Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9434fd21-4470-4941-8352-656fd7c08aeb",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start of the Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "81f1745e-ae77-4cf2-97be-7970040844f4",
            "sourceColumn": "Start of the Month",
            "summarizeBy": "none"
          },
          {
            "name": "End of the Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "4b43eff1-14a4-4be8-a84c-5dd5e97714c7",
            "sourceColumn": "End of the Month",
            "summarizeBy": "none"
          },
          {
            "name": "Days in the Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d4ef107-d00a-40f2-9246-50ae68647ae4",
            "sourceColumn": "Days in the Month",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter of Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "feb3075d-1bc0-487b-a885-6f879878271f",
            "sourceColumn": "Quarter of Year Number",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "9b954414-163c-4e4d-83c2-2ac533a238ea",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "End of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "657f144b-ce91-418d-8b1d-63d31dbe1e56",
            "sourceColumn": "End of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c9a5b42-ec09-47f5-9563-d0055c6b4f01",
            "sourceColumn": "Week of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Week of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2e0545a-2cc0-49da-a778-f62bd26d5f20",
            "sourceColumn": "Week of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b2d56c97-5747-4051-94b1-b16842620ab2",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          },
          {
            "name": "End of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c4bef3ab-fc44-4197-8419-694fa07e0f18",
            "sourceColumn": "End of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e322308d-b2c1-48e4-b0f4-1cad887722aa",
            "sourceColumn": "Day of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb93558e-c6e5-4385-a346-756a788e0036",
            "sourceColumn": "Day of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d894360-d9b3-4b3f-a747-b9e7e4ea303e",
            "sourceColumn": "Day of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "267ab26f-b025-4bd2-9e3c-1e6447830f00",
            "sourceColumn": "Day of Week Name",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "20869573-5aa7-43f5-aad4-dd6edfffba52",
            "sourceColumn": "Fiscal Year Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68fc8d76-9c6f-4199-803f-ab15669f4c6a",
            "sourceColumn": "Fiscal Year Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "200da891-c10b-4f27-9497-4de399b27e32",
            "sourceColumn": "Fiscal Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9278ddc-5632-4c4c-8b85-b415d0ddd302",
            "sourceColumn": "Fiscal Year Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "caed29d7-e35d-414c-9e67-db681ac6a9fb",
            "sourceColumn": "Fiscal Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Day Of Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "63d9e8a3-abdf-4b0e-8e73-c0caed6c5ec9",
            "sourceColumn": "Fiscal Day Of Year Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Start Of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f780dc1e-2a57-44b8-83cc-387bde792ea8",
            "sourceColumn": "Fiscal Start Of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal End Of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ceb05f1b-45a8-46c1-84d3-69fe89ac8c69",
            "sourceColumn": "Fiscal End Of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Of Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed077a60-1480-446a-8f71-4b4d25492b4b",
            "sourceColumn": "Fiscal Quarter Of Year Number",
            "summarizeBy": "none"
          },
          {
            "name": "Month Abbrev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a02292d7-baea-4078-850e-cc434ed839eb",
            "sortByColumn": "Month Number",
            "sourceColumn": "Month Abbrev",
            "summarizeBy": "none"
          },
          {
            "name": "Day Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ba1046e-e996-4e91-86a1-779dd0f8e922",
            "sourceColumn": "Day Offset",
            "summarizeBy": "none"
          },
          {
            "name": "Week Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74ac18f2-8e4f-4100-a0c8-dabb343404eb",
            "sourceColumn": "Week Offset",
            "summarizeBy": "none"
          },
          {
            "name": "Month Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aad1958c-2ce4-4609-9d69-ed949c976899",
            "sourceColumn": "Month Offset",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2bcdfafd-38a5-48a9-8993-9527dac806d2",
            "sourceColumn": "Quarter Offset",
            "summarizeBy": "none"
          },
          {
            "name": "Year Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c44127ca-dc16-40c0-9531-6432fa20f6ea",
            "sourceColumn": "Year Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Rolling Month Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67d22400-3cf0-41b1-9a89-21ba6ee43d4b",
            "sourceColumn": "Rolling Month Sort",
            "summarizeBy": "none"
          },
          {
            "name": "Rolling Month Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Calculate(MAX('Dim Date'[Month Offset]), FILTER('dim date','Dim Date'[Month Offset] <1 && 'Dim Date'[Month Offset] > -12))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1077c334-efaa-4b1e-86b9-3e82c0ff1123",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "b482ea62-ade0-46f9-ae46-b379f548f2a6",
        "partitions": [
          {
            "name": "Dim Date",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_date_Table = main_Schema{[Name=\"dim_date\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_date_Table,{\"TheDate\", \"YearNumber\", \"StartofYear\", \"EndofYear\", \"MonthNumber\", \"MonthName\", \"StartoftheMonth\", \"EndoftheMonth\", \"DaysintheMonth\", \"QuarterofYearNumber\", \"StartofQuarter\", \"EndofQuarter\", \"WeekofYear\", \"WeekofMonth\", \"StartofWeek\", \"EndofWeek\", \"DayofMonth\", \"DayofWeek\", \"DayofYear\", \"DayofWeekName\", \"FiscalYearNumber\", \"FiscalYearQuarterNumber\", \"FiscalQuarterNumber\", \"FiscalYearMonthNumber\", \"FiscalMonthNumber\", \"FiscalDayOfYearNumber\", \"FiscalStartOfYear\", \"FiscalEndOfYear\", \"FiscalQuarterOfYearNumber\", \"MonthAbbrev\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Dayof Week Name\", \"Day of Week Name\"}, {\"Dayof Year\", \"Day of Year\"}, {\"Dayof Week\", \"Day of Week\"}, {\"Dayof Month\", \"Day of Month\"}, {\"Endof Week\", \"End of Week\"}, {\"Startof Week\", \"Start of Week\"}, {\"Weekof Month\", \"Week of Month\"}, {\"Weekof Year\", \"Week of Year\"}, {\"Endof Quarter\", \"End of Quarter\"}, {\"Startof Quarter\", \"Start of Quarter\"}, {\"Quarterof Year Number\", \"Quarter of Year Number\"}, {\"Daysinthe Month\", \"Days in the Month\"}, {\"Endofthe Month\", \"End of the Month\"}, {\"Startofthe Month\", \"Start of the Month\"}, {\"Endof Year\", \"End of Year\"}, {\"Startof Year\", \"Start of Year\"}}),",
                "    #\"Today\" = Date.From(DateTime.LocalNow()),",
                "    #\"Add Day Offset\" = Table.AddColumn(#\"Renamed Columns\", \"Day Offset\", each Number.From( [The Date]-  Date.From( #\"Today\" ) )),",
                "    #\"Add Week Offset\" = Table.AddColumn(#\"Add Day Offset\", \"Week Offset\", each Duration.Days( Date.StartOfWeek( [The Date] , Day.Monday ) - Date.StartOfWeek( Today, Day.Monday ) ) / 7 , Int64.Type ),",
                "    #\"Add Month Offset\" = Table.AddColumn(#\"Add Week Offset\", \"Month Offset\", each ( [Year Number] - Date.Year( Today ) ) * 12 + ( [Month Number] - Date.Month( Today ) ), Int64.Type ),",
                "    #\"Add Quarter Offset\" = Table.AddColumn(#\"Add Month Offset\", \"Quarter Offset\", each ( [Year Number] - Date.Year(Today) ) * 4 + Date.QuarterOfYear( [The Date]  ) - Date.QuarterOfYear( Today ), Int64.Type ),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Add Quarter Offset\", \"Year Offset\", each Number.From( [Year Number] - Date.Year( #\"Today\" )  )),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Added Custom\", \"Rolling Month Sort\", each fn_RollingMonthSort([Month Number])),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Invoked Custom Function\",{{\"Rolling Month Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Employee",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c0927d0-787b-483e-99fc-7565d4e73ac8",
            "sourceColumn": "Employee Key",
            "summarizeBy": "none"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "907c29a0-8cd0-4f1e-beb6-2e01ea029d2c",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2731dd1-a8ed-4872-85c6-599de513df75",
            "sourceColumn": "Job Title Description",
            "summarizeBy": "none"
          },
          {
            "name": "FMIL Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69400ac0-7ced-4a0d-b579-287ca29e3364",
            "sourceColumn": "FMIL Name",
            "summarizeBy": "none"
          },
          {
            "name": "Pref First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41a631c4-7051-42b6-a3b3-269977a6d539",
            "sourceColumn": "Pref First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Pref Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ade9d3f-46be-4228-a0ad-f2e2560f30cf",
            "sourceColumn": "Pref Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Pref Middle Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4348d9f7-7ba4-4bd9-8f6a-8dfd82c274fd",
            "sourceColumn": "Pref Middle Name",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e420991-5b28-4826-b899-6d82b1b164e1",
            "sourceColumn": "Manager Name",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Bus Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceac2a43-d04d-4f36-ac13-8eecd24ff055",
            "sourceColumn": "Phone Bus Number",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Bus Ext Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd05e87c-9e2a-4890-b6a5-086bfc929ed6",
            "sourceColumn": "Phone Bus Ext Number",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Cell Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e018f83-6df3-4292-aaab-769fd8ecbf67",
            "sourceColumn": "Phone Cell Number",
            "summarizeBy": "none"
          },
          {
            "name": "Assistant Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ef9bf4f-e612-4fe9-ae8c-70c494233c69",
            "sourceColumn": "Assistant Name",
            "summarizeBy": "none"
          },
          {
            "name": "Assistant Phone Bus Ext Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11d6dd72-7669-417f-9c6a-5ae73a4167fc",
            "sourceColumn": "Assistant Phone Bus Ext Number",
            "summarizeBy": "none"
          },
          {
            "name": "Hours Standard Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6e195583-f525-459d-a6ac-2b172f2e70b6",
            "sourceColumn": "Hours Standard Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Eligibility Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a5a395e-07e8-4aa8-b30f-70058097015d",
            "sourceColumn": "Eligibility Year Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Associate Level Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38df5a9d-e7c9-4475-87b5-6b2db945b34c",
            "sourceColumn": "Associate Level Text",
            "summarizeBy": "none"
          },
          {
            "name": "Contract Type Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b747a75a-0b51-41dc-a50c-fe56436f7eb3",
            "sourceColumn": "Contract Type Description",
            "summarizeBy": "none"
          },
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1f5c2d7a-8030-42ae-8172-e137a464e5a3",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Full Time Equivalency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8d8004a1-14a3-4c63-b9f8-a04c875e8d1c",
            "sourceColumn": "Full Time Equivalency",
            "summarizeBy": "sum"
          },
          {
            "name": "Employee Active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "592811a9-c562-453c-9ba4-7c9213e627c6",
            "sourceColumn": "Employee Active",
            "summarizeBy": "none"
          },
          {
            "name": "Is Full Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5476a58-aa1d-4491-af1c-fdae7ee3be39",
            "sourceColumn": "Is Full Time",
            "summarizeBy": "none"
          },
          {
            "name": "Pref LFMI Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "513d5c24-400f-4464-aa6a-099ca8c61e1a",
            "sourceColumn": "Pref LFMI Name",
            "summarizeBy": "none"
          },
          {
            "name": "First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46876943-9243-4c60-bf76-8db7ecbf5956",
            "sourceColumn": "First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e67b9a8-5886-4a72-9608-1a51581a811f",
            "sourceColumn": "Employee Display Name",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Display Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00dfd62d-0ec3-4872-bb1f-1137846bf7ed",
            "sourceColumn": "Employee Display Title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bccefd35-5ddf-44c2-9845-52cd528fdeac",
        "partitions": [
          {
            "name": "Dim Employee",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_employee_Table = main_Schema{[Name=\"dim_employee\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_employee_Table,{\"EmployeeKey\", \"EmployeeID\", \"JobTitleDescription\", \"FirstName\", \"FMILName\", \"PrefFirstName\", \"PrefLastName\", \"PrefMiddleName\", \"PrefLFMIName\", \"ManagerName\", \"PhoneBusNumber\", \"PhoneBusExtNumber\", \"PhoneCellNumber\", \"AssistantName\", \"AssistantPhoneBusExtNumber\", \"HoursStandardAmount\", \"EligibilityYearNumber\", \"AssociateLevelText\", \"ContractTypeDescription\", \"isCurrentRecordFlag\", \"FullTimeEquivalency\", \"isEmployeeActive\", \"IsFullTime\", \"EmployeeDisplayName\", \"EmployeeDisplayTitle\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Employee I D\", \"Employee ID\"}, {\"F M I L Name\", \"FMIL Name\"}, {\"Pref L F M I Name\", \"Pref LFMI Name\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Matter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "369e2dec-bc29-45e8-9e55-e0bc0c737b73",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Matter ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ba33f43-33e7-4097-a864-8f9581ce1dd7",
            "sourceColumn": "Client Matter ID",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd1a6de5-1dc5-40e1-8d3c-0e7a21334f97",
            "sourceColumn": "Matter Name",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Status Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cee9936-f53e-4c5c-b011-e22464bf82c6",
            "sourceColumn": "Matter Status Description",
            "summarizeBy": "none"
          },
          {
            "name": "Opened Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dbf423ed-8b1a-4cb9-bda8-1a60abb4de8d",
            "sourceColumn": "Opened Date",
            "summarizeBy": "none"
          },
          {
            "name": "Re Opened Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "443c02de-1a5c-41e3-aaab-e136b93a3443",
            "sourceColumn": "Re Opened Date",
            "summarizeBy": "none"
          },
          {
            "name": "Inactive Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a8954ee8-892d-452f-a9bf-3ea36c2a22d3",
            "sourceColumn": "Inactive Date",
            "summarizeBy": "none"
          },
          {
            "name": "Closed Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1ff2ee3f-573b-48a5-aa77-8d8403461a85",
            "sourceColumn": "Closed Date",
            "summarizeBy": "none"
          },
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a629b7a6-eca7-49e0-b58a-4e3466bc690f",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c98e9802-7a14-4e3d-872a-9ad0e3b76f14",
            "sourceColumn": "Matter Active",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Probono",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dc7eaed-f2f2-4521-8d8b-2c82b242b9dc",
            "sourceColumn": "Matter Probono",
            "summarizeBy": "none"
          },
          {
            "name": "Is Matter Non Billable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32da1a89-8ce1-496a-8b8d-0edd48bf3e0b",
            "sourceColumn": "Is Matter Non Billable",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Admin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97ac080c-81dc-47db-8309-22c292082c7a",
            "sourceColumn": "Matter Admin",
            "summarizeBy": "none"
          },
          {
            "name": "Arrangement Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b5c87cb-61ed-45b2-bf6b-7fa479fd2b4a",
            "sourceColumn": "Arrangement Code",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23aff92e-ea8a-403b-81dd-4b246529ec0d",
            "sourceColumn": "Matter Display Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db85d621-b1b0-4a2c-8515-7daedf658c60",
        "partitions": [
          {
            "name": "Dim Matter",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_matter_Table = main_Schema{[Name=\"dim_matter\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_matter_Table,{\"MatterKey\", \"ClientMatterID\", \"MatterName\", \"MatterStatusDescription\", \"ArrangementCode\", \"OpenedDate\", \"ReOpenedDate\", \"InactiveDate\", \"ClosedDate\", \"isCurrentRecordFlag\", \"isMatterActive\", \"isMatterProbono\", \"IsMatterNonBillable\", \"isMatterAdmin\", \"MatterDisplayName\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Client Matter I D\", \"Client Matter ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Role Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Role Type Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eda04f28-4689-4400-9526-4af918cda959",
            "sourceColumn": "Role Type Key",
            "summarizeBy": "none"
          },
          {
            "name": "Role Type ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b542ce1-0a54-4858-8177-a24a6297ab99",
            "sourceColumn": "Role Type ID",
            "summarizeBy": "none"
          },
          {
            "name": "Role Type Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b6b8c45-c378-4c5b-b262-962fdae3cff7",
            "sourceColumn": "Role Type Description",
            "summarizeBy": "none"
          },
          {
            "name": "Firm Role Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae97ed51-8ae9-4c55-ba5a-1cc54ac989e6",
            "sourceColumn": "Firm Role Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c98940b4-165b-4af3-bc4a-5b3c47764822",
        "partitions": [
          {
            "name": "Dim Role Type",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_roletype_Table = main_Schema{[Name=\"dim_roletype\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_roletype_Table,{\"RoleTypeKey\", \"RoleTypeID\", \"RoleTypeDescription\", \"FirmRoleDescription\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Role Type I D\", \"Role Type ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Timesheet",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Timesheet Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ca1a840-2da4-4dcb-bc1e-3ded46429b2b",
            "sourceColumn": "Timesheet Key",
            "summarizeBy": "none"
          },
          {
            "name": "Time Transaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9eb05da0-2da8-4d02-8580-62ffd8e95399",
            "sourceColumn": "Time Transaction ID",
            "summarizeBy": "count"
          },
          {
            "name": "Time Index ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f592e9c-8092-491c-a708-87eb0916c618",
            "sourceColumn": "Time Index ID",
            "summarizeBy": "count"
          },
          {
            "name": "Time Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc3ebf18-957e-474a-9dc2-09fd8e5c793d",
            "sourceColumn": "Time Description",
            "summarizeBy": "none"
          },
          {
            "name": "Phase Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09bd16b3-e386-431f-94a4-1902b591abff",
            "sourceColumn": "Phase Description",
            "summarizeBy": "none"
          },
          {
            "name": "Task Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4b735a9-d15f-4117-a085-9d267f69157b",
            "sourceColumn": "Task Description",
            "summarizeBy": "none"
          },
          {
            "name": "Activity Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "268a5f55-d2c3-49bf-88d8-e779e95b27df",
            "sourceColumn": "Activity Description",
            "summarizeBy": "none"
          },
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8414d8ca-dd65-49b4-91af-ff70d9922699",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Time Card Active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7676f1a6-005f-4a62-bc60-b288f6b03977",
            "sourceColumn": "Time Card Active",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a369ee6e-4a91-42ee-bf1c-40b5088814aa",
        "partitions": [
          {
            "name": "Dim Timesheet",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_timesheet_Table = main_Schema{[Name=\"dim_timesheet\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_timesheet_Table,{\"TimesheetKey\", \"TimeTransactionID\", \"TimeIndexID\", \"TimeDescription\", \"PhaseDescription\", \"TaskDescription\", \"ActivityDescription\", \"isCurrentRecordFlag\", \"isTimeCardActive\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Time Transaction I D\", \"Time Transaction ID\"}, {\"Time Index I D\", \"Time Index ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Invoice Transactions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4c9b687-fe06-4fbc-9950-a69bd2769296",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "568be499-af10-453c-9ff3-b1a1db87c1ef",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30934d19-884a-404d-98ae-09f7252b0be5",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "efe15e31-8f83-4e96-86ad-dab28099a077",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ae9422f-d174-4e5a-9db6-0471b197e908",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Create Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "db35f475-bd3c-442e-813e-e7aa21bf0048",
            "sourceColumn": "Invoice Create Date",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Due Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e6851bbb-8d6b-4561-8ad9-ad145d435f33",
            "sourceColumn": "Invoice Due Date",
            "summarizeBy": "none"
          },
          {
            "name": "Last Invoice Receipt Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "69748853-e7b1-4d58-b02d-889e488c13bb",
            "sourceColumn": "Last Invoice Receipt Date",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Total Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43830238-3b1c-4a78-82b7-97fcd8ad2547",
            "sourceColumn": "Invoice Total Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Fee Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "371587e4-8581-474f-8e32-116f4364191c",
            "sourceColumn": "Invoice Fee Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Std Fee Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a9fcda0d-a315-4cf1-bbf4-a54e6dc32e09",
            "sourceColumn": "Invoice Std Fee Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Hard Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1ef37cfb-1953-4510-9115-d7aa04ebf453",
            "sourceColumn": "Invoice Hard Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Soft Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "24da904c-bd11-464b-b110-a7851c9ee176",
            "sourceColumn": "Invoice Soft Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5f6e4eb-2932-4950-af02-0a56d17f4378",
            "sourceColumn": "Invoice Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Int Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67b9b9e0-9d68-4406-859f-c04e129cdcf1",
            "sourceColumn": "Invoice Int Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice BOA Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "53196c72-688b-4203-b35e-570ab2299969",
            "sourceColumn": "Invoice BOA Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Other Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fce74d30-9230-4d3d-a48a-353c44f81102",
            "sourceColumn": "Invoice Other Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Balance Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "98ffa6ed-ef96-4e1b-a33b-36384726d1cb",
            "sourceColumn": "Invoice Balance Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Fees Write Up Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e0975876-de23-40b0-bbcb-b142e5628b9d",
            "sourceColumn": "Invoice Fees Write Up Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Fees Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93dfef0c-f98b-448a-95bb-c5ebcad656d0",
            "sourceColumn": "Invoice Fees Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Hard Cost Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27120bf2-5ff7-4454-a3d8-266360fe1515",
            "sourceColumn": "Invoice Hard Cost Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Soft Cost Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "87df0305-636b-44e7-aec2-1e973f11866a",
            "sourceColumn": "Invoice Soft Cost Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1a76aa50-9c9d-4b52-b2cf-5dcf092007f4",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3ba2e797-b4ec-4249-af9b-bb9a2c58d985",
        "partitions": [
          {
            "name": "Fact Invoice Transactions",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_invoicetransactions_Table = main_Schema{[Name=\"fact_invoicetransactions\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fact_invoicetransactions_Table,{\"InvoiceKey\", \"ClientKey\", \"MatterKey\", \"PracticeGroupKey\", \"OfficeKey\", \"InvoiceCreateDate\", \"InvoiceDueDate\", \"LastInvoiceReceiptDate\", \"InvoiceTotalAmount\", \"InvoiceFeeAmount\", \"InvoiceStdFeeAmount\", \"InvoiceHardCostAmount\", \"InvoiceSoftCostAmount\", \"InvoiceTaxAmount\", \"InvoiceIntAmount\", \"InvoiceBOAAmount\", \"InvoiceOtherAmount\", \"InvoiceBalanceAmount\", \"InvoiceFeesWriteUpAmount\", \"InvoiceFeesWriteDownAmount\", \"InvoiceHardCostWriteDownAmount\", \"InvoiceSoftCostWriteDownAmount\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Invoice B O A Amount\", \"Invoice BOA Amount\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Discount\", each if [Invoice Fee Amount] >  [Invoice Std Fee Amount] then 0 else [Invoice Std Fee Amount] - [Invoice Fee Amount]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Discount\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Matter Snapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "005c0619-6d3e-48ff-9e40-01f8b21af73f",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "93f51e5b-a5f0-406c-92bd-57e59710743c",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1666a009-9ffd-4c22-9d75-2ad3bec206bb",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9bd1ffd9-129c-48d3-a5a0-94651bac835b",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Last Bill Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "82ae70ee-82d5-4b39-b206-d3c5b5edbdf8",
            "sourceColumn": "Matter Last Bill Date",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Last Payment Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dca90391-fddb-4651-b7e7-e3614823cff6",
            "sourceColumn": "Matter Last Payment Date",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Last Time Entry Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "300914b4-6992-498d-8968-6decf34ac19d",
            "sourceColumn": "Matter Last Time Entry Date",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Last WIP Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c862ea8-c641-43bb-83ef-7aba69d3c603",
            "sourceColumn": "Matter Last WIP Date",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Fees Billed Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "21d4e9cf-b7d3-4565-9c90-ca2c873579d1",
            "sourceColumn": "Matter Fees Billed Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Matter Fees Collected Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54a240e9-2dfa-49b5-bb3e-3dce794a2574",
            "sourceColumn": "Matter Fees Collected Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Matter WIP Total Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4607b2f7-2a61-4841-82bf-4a96bf4f3558",
            "sourceColumn": "Matter WIP Total Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Matter AR Total Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc371ee3-dc38-4a81-9795-b85aa4fbece1",
            "sourceColumn": "Matter AR Total Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Matter As of Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "524e61f1-1fd6-4d9d-bc19-7629bba16a1b",
            "sourceColumn": "Matter As of Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f594a6e8-149b-471e-9e2e-8edfa0f29989",
        "partitions": [
          {
            "name": "Fact Matter Snapshot",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_mattersnapshot_Table = main_Schema{[Name=\"fact_mattersnapshot\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fact_mattersnapshot_Table,{\"MatterKey\", \"ClientKey\", \"PracticeGroupKey\", \"OfficeKey\", \"MatterLastBillDate\", \"MatterLastPaymentDate\", \"MatterLastTimeEntryDate\", \"MatterLastWIPDate\", \"MatterFeesBilledAmount\", \"MatterFeesCollectedAmount\", \"MatterWIPTotalAmount\", \"MatterARTotalAmount\", \"MatterAsofDate\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Matter Last W I P Date\", \"Matter Last WIP Date\"}, {\"Matter W I P Total Amount\", \"Matter WIP Total Amount\"}, {\"Matter A R Total Amount\", \"Matter AR Total Amount\"}, {\"Matter Asof Date\", \"Matter As of Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Bridge Matter Roles",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Role Type Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2dbdd7f-3b38-4e22-9a08-c7874fb39895",
            "sourceColumn": "Role Type Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34be8f62-3137-4dd8-83b4-fb4d3f0d539c",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db90416f-68c7-4bb4-81e9-68bbd9dd62fc",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b855a39-dd91-4dae-9c8e-5362be26c221",
            "sourceColumn": "Employee Key",
            "summarizeBy": "none"
          },
          {
            "name": "Participating Weight Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39eb0976-3eb9-4f50-8bec-35d5ba2781e7",
            "sourceColumn": "Participating Weight Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3f0841d0-d98b-4e92-bd15-666911b57235",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3167f8e4-5f37-4b33-9dbe-319264565e59",
        "partitions": [
          {
            "name": "Bridge Matter Roles",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    bridge_matterroles_Table = main_Schema{[Name=\"bridge_matterroles\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(bridge_matterroles_Table,{\"RoleTypeKey\", \"ClientKey\", \"MatterKey\", \"EmployeeKey\", \"ParticipatingWeightNumber\", \"isCurrentRecordFlag\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Timesheet",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Timesheet Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81d1e852-c941-4917-b832-6cdf0ad08e7b",
            "sourceColumn": "Timesheet Key",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f24fd411-daf3-40e8-bf2a-930309029bc5",
            "sourceColumn": "Employee Key",
            "summarizeBy": "count"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b38af879-f67d-4eb0-aead-fa0ad1294070",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "193c7c42-e17e-4de0-bee2-e536f776beb4",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01aa8608-91e0-42ea-86a3-d05b04cc36e8",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4e9701b-da87-4d10-afb5-bfd5a576cbdb",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Time Worked Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1f70983b-2fa8-4ac3-9ae6-15bbcb464176",
            "sourceColumn": "Time Worked Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time Submitted Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9a6f7dd-6f4d-425a-b3f0-82669da0ee5a",
            "sourceColumn": "Time Submitted Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time Posted Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1881142a-116f-42dc-a1a1-d8d107a22849",
            "sourceColumn": "Time Posted Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time Total Hours Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d0677a7a-b790-4d09-b48c-209f773071a2",
            "sourceColumn": "Time Total Hours Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Total Fees Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d4c5434a-62d0-42e0-9099-73d2871de2af",
            "sourceColumn": "Time Total Fees Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Total Std Fees Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79eeda10-7e4c-4cd7-81b9-d12cfcdd5cac",
            "sourceColumn": "Time Total Std Fees Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Hours to Bill Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77ef8acf-9292-4923-aaad-28dfd0b2ee8b",
            "sourceColumn": "Time Hours to Bill Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Fees to Bill Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d882597b-f5f1-4cd5-988d-c5b164657b8b",
            "sourceColumn": "Time Fees to Bill Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Total Hours Relieved Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64be0e29-86f9-47ba-aa7f-018f3ebd78fb",
            "sourceColumn": "Time Total Hours Relieved Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Total Fees Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6903f79-1019-43eb-850f-03242394cfc3",
            "sourceColumn": "Time Total Fees Relieved Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Total Std Fees Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "45d40343-7987-4aef-ab39-3bd61172a5e4",
            "sourceColumn": "Time Total Std Fees Relieved Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Hours to Bill Relieved Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd43d3cf-3403-4a47-bcd7-b4d6d003feef",
            "sourceColumn": "Time Hours to Bill Relieved Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Time Fees to Bill Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "be5383df-0f9d-46b8-97cc-355566efc45c",
            "sourceColumn": "Time Fees to Bill Relieved Amount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2b461abc-6923-470d-af5f-c3cd1118d46d",
        "partitions": [
          {
            "name": "Fact Timesheet",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    DateLimit = Date.AddYears(Date.From(DateTime.LocalNow()),-2),",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_timesheettransactions_Table = main_Schema{[Name=\"fact_timesheettransactions\",Kind=\"Table\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(fact_timesheettransactions_Table, each [TimeWorkedDate] > DateLimit),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"TimesheetKey\", \"EmployeeKey\", \"ClientKey\", \"MatterKey\", \"PracticeGroupKey\", \"OfficeKey\", \"TimeWorkedDate\", \"TimeSubmittedDate\", \"TimePostedDate\", \"TimeTotalHoursNumber\", \"TimeTotalFeesAmount\", \"TimeTotalStdFeesAmount\", \"TimeHourstoBillNumber\", \"TimeFeestoBillAmount\", \"TimeTotalHoursRelievedNumber\", \"TimeTotalFeesRelievedAmount\", \"TimeTotalStdFeesRelievedAmount\", \"TimeHourstoBillRelievedNumber\", \"TimeFeestoBillRelievedAmount\"})",
                ",",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Time Hoursto Bill Number\", \"Time Hours to Bill Number\"}, {\"Time Feesto Bill Amount\", \"Time Fees to Bill Amount\"}, {\"Time Hoursto Bill Relieved Number\", \"Time Hours to Bill Relieved Number\"}, {\"Time Feesto Bill Relieved Amount\", \"Time Fees to Bill Relieved Amount\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Timeframe Selection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Timeframe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a52163c5-2210-412c-ba05-72a62f60cc89",
            "sortByColumn": "Index",
            "sourceColumn": "Timeframe",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dac8cc08-2930-49be-a47a-ae2ec2ae5f62",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d392a4fe-c858-4f8c-92e7-c592ef4c35e0",
        "partitions": [
          {
            "name": "Timeframe Selection",
            "mode": "import",
            "queryGroup": "PBI Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8g1xUYrViVaKhNJBhkZgOiC1KC2/KDcxLzlVITI1sUgpNhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Timeframe = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Timeframe\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Proforma",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Proforma Index ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a66a963a-5951-4454-8e25-544a0b499e91",
            "sourceColumn": "Proforma Index ID",
            "summarizeBy": "none"
          },
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f70fac6b-e1cc-43b8-8441-cc50f6c00d4a",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Status Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff566581-7d20-47e2-99a1-44f9e0b387e8",
            "sortByColumn": "Status Order",
            "sourceColumn": "Proforma Status Category",
            "summarizeBy": "none"
          },
          {
            "name": "Status Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3cc02789-fcf6-486b-bcb2-deb512a12374",
            "sourceColumn": "Status Order",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Tier Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "281947fa-dc2e-4fc1-82a4-f772aa27621f",
            "sourceColumn": "Proforma Tier Name",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Status Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea258741-bf2a-4751-8ed1-eca8534a174d",
            "sourceColumn": "Proforma Status Code",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Billing Status Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed8c9434-e546-4d1b-a38d-ad09f7e48a1c",
            "sourceColumn": "Proforma Billing Status Code",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ba0958de-37d5-4588-bc0e-82c1ddf2f82a",
            "sourceColumn": "Proforma Key",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2db5c9a-41b1-40d9-acfe-23eb716f2961",
            "sourceColumn": "Proforma Code",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5cff5f9-0245-4d92-9b58-0971258d32d9",
            "sourceColumn": "Proforma Description",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma  Tier Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "122c6248-043f-47e9-b05f-d895c8838bf3",
            "sourceColumn": "Proforma  Tier Description",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Status Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d26f772-5679-4632-86fd-b362b46a28d2",
            "sourceColumn": "Proforma Status Description",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Responsible Party Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4a8cbcd-e411-48b6-973c-1c10f53a803d",
            "sourceColumn": "Proforma Responsible Party Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "721a1790-da96-4132-857f-0fb9aff7a8d2",
        "partitions": [
          {
            "name": "Dim Proforma",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_proforma_Table = main_Schema{[Name=\"dim_proforma\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_proforma_Table,{\"ProformaKey\", \"ProformaIndexID\", \"ProformaCode\", \"ProformaDescription\", \"ProformaTier\", \"ProformaStatusDescription\", \"ProformaResponsiblePartyDescription\", \"isCurrentRecordFlag\", \"ProformaStatusCode\", \"ProformaBillingStatusCode\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Add Spaces\",{{\"Proforma Index I D\", \"Proforma Index ID\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns1\", \"Proforma Status Category\", each if [Proforma Status Code] = \"CURRENT\" then \"Generated\" else if [Proforma Status Code] = \"CURR_IN_PROGESS\" then \"In Progress\" else if [Proforma Status Code] = \"PRINTED\" then \"In Progress\" else if [Proforma Status Code] = \"RFA\" then \"In Progress\" else if [Proforma Status Code] = \"RFR\" then \"In Progress\" else if [Proforma Status Code] = \"FAR\" then \"In Progress\" else if [Proforma Status Code] = \"HBO\" then \"Held\" else if [Proforma Status Description] = \"Billed\" then \"Billed\" else if [Proforma Status Code] = \"RFB_URGENT\" then \"Ready for Billers\" else if [Proforma Status Code] = \"RFB\" then \"Ready for Billers\" else if [Proforma Status Code] = \"PENDINGAPPR\" then \"Pending WD Approval\" else if [Proforma Status Code] = \"BIP\" then \"Biller - In Process\" else if [Proforma Status Code] = \"DRAFT\" then \"Biller - In Process\" else if [Proforma Code] = \"HOLD\" then \"Biller - In Process\" else if [Proforma Status Code] = \"INFO\" then \"System\" else if [Proforma Status Code] = \"NONBILLABLE\" then \"System\" else if [Proforma Status Code] = \"Close\" then \"System\" else if [Proforma Status Code] = \"PREVIOUS\" then \"System\" else \"Not Specified\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"Proforma Status Category\", type text}}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type\", \"Status Order\", each if [Proforma Status Category] = \"Generated\" then 1 else if [Proforma Status Category] = \"In Progress\" then 2 else if [Proforma Status Category] = \"Held\" then 3 else if [Proforma Status Category] = \"Ready for Billers\" then 4 else if [Proforma Status Category] = \"Biller - In Process\" then 5 else if [Proforma Status Category] = \"Pending WD Approval\" then 6 else if [Proforma Status Category] = \"Ready for Billers\" then 7 else if Text.StartsWith([Proforma Status Category], \"Billed\") then 8 else 9),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"Status Order\", Int64.Type}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\",{{\"Proforma Tier\", \"Proforma  Tier Description\"}}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Renamed Columns2\", \"Text Before Delimiter\", each Text.BeforeDelimiter([Proforma  Tier Description], \" (\"), type text),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Text Before Delimiter\",{{\"Text Before Delimiter\", \"Proforma Tier Name\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Invoice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2f0c3a4-ac46-47c1-985a-6876820b98a4",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8e2fd03-9778-4da8-a557-f5122e95d688",
            "sourceColumn": "Invoice Number",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Index ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ac09a2e-6f81-4f78-b48c-8a83a8616d1a",
            "sourceColumn": "Invoice Index ID",
            "summarizeBy": "count"
          },
          {
            "name": "Invoice Paid Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d1ecd159-88a3-45ae-96ea-d32c0cf0d297",
            "sourceColumn": "Invoice Paid Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Current Record Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4db73a46-980f-4f3e-a883-9e0fb2901ab4",
            "sourceColumn": "Current Record Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "695b7776-84c3-4eb0-a324-5a33b69bc53d",
            "sourceColumn": "Invoice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Paid Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c655849d-6e2c-4380-8468-e95b48360c37",
            "sourceColumn": "Invoice Paid Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fe92d340-57bf-4198-8b4c-572e91682a70",
        "partitions": [
          {
            "name": "Dim Invoice",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "   gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_invoice_Table = main_Schema{[Name=\"dim_invoice\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_invoice_Table,{\"InvoiceKey\", \"InvoiceNumber\", \"InvoiceIndexID\", \"isInvoicePaidFlag\", \"isCurrentRecordFlag\", \"InvoiceDate\", \"InvoicePaidDate\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Invoice Index I D\", \"Invoice Index ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Proforma Transactions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Proforma Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "debe4ba8-e560-449b-87ef-6d7d25d7f8f7",
            "sourceColumn": "Proforma Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c70a51a-f287-4e19-8543-ac1b5724a9e6",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5d960f8-5114-423f-9cd0-c3927f3ef5b5",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "edc449a8-8c0c-4224-bcd7-186b91588a69",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "count"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78c1b708-aa3d-4622-9d11-35b2621953fc",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "426938a7-f3a1-407a-9bc4-aa6c473a46e1",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "10a3d352-8029-4ca8-9f69-4c0b1564a33a",
            "sourceColumn": "Proforma Date",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma RFB Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "92871666-7352-490a-91af-797d697cc277",
            "sourceColumn": "Proforma RFB Date",
            "summarizeBy": "none"
          },
          {
            "name": "Proforma Total Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ca78f415-a371-4f62-9458-9d363f9ceafd",
            "sourceColumn": "Proforma Total Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma Fees Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "528542e2-06ce-4dea-97fd-b6cc1b386c07",
            "sourceColumn": "Proforma Fees Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma Hard Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b82ddb69-fa1d-42f7-9beb-69f55d464dd8",
            "sourceColumn": "Proforma Hard Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma Soft Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4897a802-d443-4679-8763-1c647bd2e2e4",
            "sourceColumn": "Proforma Soft Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma B O A Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fe30f7f4-b312-4e49-b0a6-a2088c0a3028",
            "sourceColumn": "Proforma B O A Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f0ab0179-d22c-4e43-b541-429734b36dce",
            "sourceColumn": "Proforma Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma INT Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9f16e048-5ef4-4228-8dfe-341ac38ffc68",
            "sourceColumn": "Proforma INT Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Proforma Other Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "24877618-ee18-49eb-b86c-5559ca227640",
            "sourceColumn": "Proforma Other Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Generated Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "5298fbc2-4be1-41ae-97a9-d74331adf6f1",
            "sourceColumn": "Invoice Generated Date",
            "summarizeBy": "none"
          },
          {
            "name": "Attorney Complete Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ad888f10-1735-4e70-b6b5-e0c70508f81c",
            "sourceColumn": "Attorney Complete Date",
            "summarizeBy": "none"
          },
          {
            "name": "Accounting Complete Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "609d204a-4d5e-4bcd-a6f8-5192e8b25ecd",
            "sourceColumn": "Accounting Complete Date",
            "summarizeBy": "none"
          },
          {
            "name": "Total Days to Bill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d628699-009f-4923-afc4-74f5ff66125c",
            "sourceColumn": "Total Days to Bill",
            "summarizeBy": "sum"
          },
          {
            "name": "Accounting Days To Bill Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90f84c78-5a8a-4d74-a6a6-9e6e5430acc7",
            "sourceColumn": "Accounting Days To Bill Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "803f987d-e39e-4fcf-973c-b185de000ca9",
        "partitions": [
          {
            "name": "Fact Proforma Transactions",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_proformatransactions_Table = main_Schema{[Name=\"fact_proformatransactions\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fact_proformatransactions_Table,{\"ProformaKey\", \"ClientKey\", \"MatterKey\", \"InvoiceKey\", \"PracticeGroupKey\", \"OfficeKey\", \"ProformaDate\", \"ProformaRFBDate\", \"ProformaTotalAmount\", \"ProformaFeesAmount\", \"ProformaHardCostAmount\", \"ProformaSoftCostAmount\", \"ProformaBOAAmount\", \"ProformaTaxAmount\", \"ProformaINTAmount\", \"ProformaOtherAmount\", \"InvoiceGeneratedDate\", \"AttorneyCompleteDate\", \"AccountingCompleteDate\", \"AccountingDaysToBillNumber\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Proforma R F B Date\", \"Proforma RFB Date\"}, {\"Proforma I N T Amount\", \"Proforma INT Amount\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Total Days to Bill\", each Duration.Days([Invoice Generated Date] - [Proforma Date])),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Total Days to Bill\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0f86f4a28f464789a5e76ced9a63def7"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7858e72e-1c06-4ba8-b7d5-e9675e5f1aa5",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b1e12f03-6a54-4eda-b72e-b78e7264bd8a",
        "measures": [
          {
            "name": "Partner Flight Risks",
            "displayFolder": "Alerts",
            "expression": "5",
            "formatString": "#,##0",
            "lineageTag": "e7666129-4048-47c4-8fe8-542d387a12a9"
          },
          {
            "name": "Expense Overruns > 20k",
            "displayFolder": "Alerts",
            "expression": "31",
            "formatString": "#,##0",
            "lineageTag": "dcc7503b-6577-4833-b0e6-5a884c3dc0c4"
          },
          {
            "name": "UBT Matters Over 90 Days + >50k",
            "displayFolder": "Alerts",
            "expression": "12",
            "formatString": "#,##0",
            "lineageTag": "3224f596-36e4-4e6f-a102-7c322ec7452a"
          },
          {
            "name": "WIP > 75k",
            "displayFolder": "Alerts",
            "expression": "46",
            "formatString": "#,##0",
            "lineageTag": "ce351ff8-1fdf-4689-82ae-efed37cae8a6"
          },
          {
            "name": "Fees Collected",
            "displayFolder": "Collections",
            "expression": "Sum('Fact Receipt Transactions'[Receipt Fee Amount])",
            "formatString": "#,##0",
            "lineageTag": "e67db0f5-7d1b-4d8e-b3cd-a6ca024ce454"
          },
          {
            "name": "Timeframe selected",
            "displayFolder": "Collections",
            "expression": "SELECTEDVALUE('Timeframe Selection'[Timeframe])",
            "lineageTag": "c6a6f269-6da6-4bda-be4d-5d6934009a9a"
          },
          {
            "name": "Fees Collected - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "/*var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Fees Collected], 'Dim Date'[Date])",
              "var _mtd = TOTALMTD([Fees Collected], 'Dim Date'[Date])",
              "var _py = CALCULATE([Fees Collected], PREVIOUSYEAR('Dim Date'[Date]))",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"PY\", _py, BLANK()",
              ")*/",
              "var _result = SUm('ClientMatterMetrics'[FeesCollectedActual])",
              "RETURN _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "c8e64f15-5217-4f1f-86ea-0fb3744d0314"
          },
          {
            "name": "Cash Collections Actual",
            "displayFolder": "Collections",
            "expression": "Sum('Fact Receipt Transactions'[Receipt Total Amount])",
            "formatString": "#,##0",
            "lineageTag": "71c7fe45-fcc2-4112-8e6d-1e4cc3c70a63"
          },
          {
            "name": "Cash Collections - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Cash Collections Actual], 'Dim Date'[The Date])",
              "var _mtd = TOTALMTD([Cash Collections Actual], 'Dim Date'[The Date])",
              "var _py = CALCULATE([Cash Collections Actual], PREVIOUSYEAR('Dim Date'[The Date]))",
              "var _minr12 = Calculate(Min('Dim Date'[The Date]), REMOVEFILTERS('Dim Date'[The Date]), 'Dim Date'[Month Offset] = -11)",
              "var _EOM = CALCULATE(Min('Dim Date'[End of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _r12 = CALCULATE([Cash Collections Actual], DATESBETWEEN('Dim Date'[The Date], _minr12, _EOM)) ",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"Performance Year\", _py,",
              "\"R12\", _r12, ",
              " BLANK()",
              ")",
              "",
              "RETURN _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "c3128cff-90ac-4606-9ab9-5e73e079524c"
          },
          {
            "name": "Cash Collections Budget - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Target - Fees Collected], 'Dim Date'[The Date])",
              "var _mtd = TOTALMTD([Target - Fees Collected], 'Dim Date'[The Date])",
              "var _py = CALCULATE([Target - Fees Collected],  REMOVEFILTERS('Dim Date'[The Date]),'Dim Date'[Year Offset] = 0)",
              "var _minr12 = Calculate(Min('Dim Date'[The Date]), REMOVEFILTERS('Dim Date'[The Date]), 'Dim Date'[Month Offset] = -11)",
              "var _EOM = CALCULATE(Min('Dim Date'[End of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _r12 = CALCULATE([Target - Fees Collected], DATESBETWEEN('Dim Date'[The Date], _minr12, _EOM)) ",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"Performance Year\", _py,",
              "\"R12\", _r12, ",
              " BLANK()",
              ")",
              "RETURN _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "196318cb-3ab1-484e-992b-7d1c4d470187"
          },
          {
            "name": "Cash Collections Proj - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "VAR _tf = [Timeframe selected]",
              "VAR _ytd = [Cash Collections Budget - Timeframe]",
              "VAR _mtd = [Cash Collections Budget - Timeframe]",
              "VAR _pya =",
              "    CALCULATE (",
              "        [Cash Collections Actual],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _pyb =",
              "    CALCULATE (",
              "        [Cash Collections Budget - Timeframe],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[The Date] > TODAY (),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _minr12 =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[The Date] ),",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Month Offset] = -11",
              "    )",
              "VAR _r12 =",
              "    CALCULATE (",
              "        [Cash Collections Actual],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], _minr12, TODAY () )",
              "    )",
              "VAR _EOM =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[End of the Month] ),",
              "        'Dim Date'[The Date] = TODAY ()",
              "    )",
              "VAR _budeom =",
              "    CALCULATE (",
              "        [Cash Collections Actual],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], TODAY (), _EOM )",
              "    )",
              "VAR _result =",
              "    SWITCH (",
              "        _tf,",
              "        \"YTD\", _ytd,",
              "        \"MTD\", _mtd,",
              "        \"R12\", _r12,",
              "        \"Performance Year\", _pya + _pyb,",
              "        BLANK ()",
              "    )",
              "RETURN",
              "    _result",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "89b2496f-110e-4cc6-a56b-b50efe0214f3"
          },
          {
            "name": "AR",
            "displayFolder": "Collections",
            "expression": "Sum('Fact AR Snapshot'[AR Amount])",
            "formatString": "#,##0",
            "lineageTag": "5e0b0eaa-553e-4d32-9f1e-c692bf288915"
          },
          {
            "name": "WIP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Collections",
            "expression": "Sum('ClientMatterMetrics'[WIP])",
            "formatString": "#,##0",
            "lineageTag": "3f837f43-3f83-4a8a-87ba-404cf5ee3847"
          },
          {
            "name": "Turnover Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Collections",
            "expression": "Average('ClientMatterMetrics'[Turnover])",
            "formatString": "#,##0.00",
            "lineageTag": "70922a64-8eee-46d7-b194-f0a615bb0ecd"
          },
          {
            "name": "Fees Worked",
            "displayFolder": "Collections",
            "expression": "Sum('Fact Proforma Transactions'[Proforma Fees Amount])",
            "formatString": "#,##0",
            "lineageTag": "01d84e1d-859c-4f94-ad77-99e7385151e7"
          },
          {
            "name": "Fees Worked - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "/*var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Fees Worked], 'Dim Date'[Date])",
              "var _mtd = TOTALMTD([Fees Worked], 'Dim Date'[Date])",
              "var _py = CALCULATE([Fees Worked], PREVIOUSYEAR('Dim Date'[Date]))",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"PY\", _py, BLANK()",
              ")*/",
              "var _result = Sum('ClientMatterMetrics'[FeesWorkedActual])",
              "RETURN _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "17a48295-82ba-48cb-85e5-eac53ba08285"
          },
          {
            "name": "Fees Worked Budget - Timeframe",
            "displayFolder": "Collections",
            "expression": "1",
            "formatString": "#,##0",
            "lineageTag": "77a58ddd-7e27-4b8d-85ca-92abc871bdab"
          },
          {
            "name": "Fees Worked Projected - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "VAR _tf = [Timeframe selected]",
              "VAR _ytd = [Fees Worked Budget - Timeframe]",
              "VAR _mtd = [Fees Worked Budget - Timeframe]",
              "VAR _pya =",
              "    CALCULATE (",
              "        [Fees Worked],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _pyb =",
              "    CALCULATE (",
              "        [Fees Worked Budget - Timeframe],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[The Date] > TODAY (),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _minr12 =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[The Date] ),",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Month Offset] = -11",
              "    )",
              "VAR _r12 =",
              "    CALCULATE (",
              "        [Fees Worked],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], _minr12, TODAY () )",
              "    )",
              "VAR _EOM =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[End of the Month] ),",
              "        'Dim Date'[The Date] = TODAY ()",
              "    )",
              "VAR _budeom =",
              "    CALCULATE (",
              "        [Fees Worked],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], TODAY (), _EOM )",
              "    )",
              "VAR _result =",
              "    SWITCH (",
              "        _tf,",
              "        \"YTD\", _ytd,",
              "        \"MTD\", _mtd,",
              "        \"R12\", _r12,",
              "        \"Performance Year\", _pya + _pyb,",
              "        BLANK ()",
              "    )",
              "RETURN",
              "    _result",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "d34d8631-5e72-401f-bbe1-6495c45cf472"
          },
          {
            "name": "Fees Worked Prior Year - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              " var _py = CALCULATE(",
              "    [Fees Worked - Timeframe],",
              "    DATEADD('Dim Date'[The Date],-1,YEAR))",
              "RETURN _py",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "98499a60-c140-425a-92ed-71ceb7146a6a"
          },
          {
            "name": "Fees Collected Budget - Timeframe",
            "displayFolder": "Collections",
            "expression": "1",
            "formatString": "#,##0",
            "lineageTag": "c19252ac-2f40-47a8-96d1-1a8f6703aa30"
          },
          {
            "name": "Fees Collected Projected - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "VAR _tf = [Timeframe selected]",
              "VAR _ytd = [Fees Collected Budget - Timeframe]",
              "VAR _mtd = [Fees Collected Budget - Timeframe]",
              "VAR _pya =",
              "    CALCULATE (",
              "        [Fees Collected],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _pyb =",
              "    CALCULATE (",
              "        [Fees Collected Budget - Timeframe],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[The Date] > TODAY (),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _minr12 =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[The Date] ),",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Month Offset] = -11",
              "    )",
              "VAR _r12 =",
              "    CALCULATE (",
              "        [Fees Collected],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], _minr12, TODAY () )",
              "    )",
              "VAR _EOM =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[End of the Month] ),",
              "        'Dim Date'[The Date] = TODAY ()",
              "    )",
              "VAR _budeom =",
              "    CALCULATE (",
              "        [Fees Collected],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], TODAY (), _EOM )",
              "    )",
              "VAR _result =",
              "    SWITCH (",
              "        _tf,",
              "        \"YTD\", _ytd,",
              "        \"MTD\", _mtd,",
              "        \"R12\", _r12,",
              "        \"Performance Year\", _pya + _pyb,",
              "        BLANK ()",
              "    )",
              "RETURN",
              "    _result",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "0ae9b0be-4c76-4489-9c76-ba2a0117bfa0"
          },
          {
            "name": "Fees Collected Prior Year - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              " var _py = CALCULATE(",
              "    [Fees Collected - Timeframe],",
              "    DATEADD('Dim Date'[The Date],-1,YEAR))",
              "RETURN _py",
              "",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "64fcf3eb-8ad7-41cc-ad5c-88c1c57777bb"
          },
          {
            "name": "Expenses",
            "displayFolder": "Expenses",
            "expression": "2367279",
            "formatString": "#,##0",
            "lineageTag": "8e86449e-60f1-4bfa-b31d-a7c85143dd5c"
          },
          {
            "name": "Expenses - Timeframe",
            "displayFolder": "Expenses",
            "expression": "Sum('ClientMatterMetrics'[ExpensesAct])",
            "formatString": "#,##0",
            "lineageTag": "3d5913db-bc79-4f31-b7b4-eacd6bf8a08b"
          },
          {
            "name": "Expenses Budget - Timeframe",
            "displayFolder": "Expenses",
            "expression": "1",
            "formatString": "#,##0",
            "lineageTag": "f7257bcb-bd3d-44cb-be73-72b6993b7239"
          },
          {
            "name": "Expenses Projected - Timeframe",
            "displayFolder": "Expenses",
            "expression": "sum('ClientMatterMetrics'[ExpensesProj])",
            "formatString": "#,##0",
            "lineageTag": "42bc2b2e-29ee-464d-ad7e-ee6837bf3c74"
          },
          {
            "name": "Expenses Prior Year - Timeframe",
            "displayFolder": "Expenses",
            "expression": "Sum('ClientMatterMetrics'[ExpensesPY])",
            "formatString": "#,##0",
            "lineageTag": "c7081198-aa0a-464a-82db-fe362f7e6343"
          },
          {
            "name": "Net Income",
            "displayFolder": "Net Income",
            "expression": [
              "1",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "9621e6a9-ea8e-4765-9a75-090d97535ee2"
          },
          {
            "name": "Net Income - Timeframe",
            "displayFolder": "Net Income",
            "expression": "Sum('ClientMatterMetrics'[NetIncomeAct])",
            "formatString": "#,##0",
            "lineageTag": "a26a68a4-993d-4d91-b936-d3dadb3a8a4c"
          },
          {
            "name": "Net Income Budget - Timeframe",
            "displayFolder": "Net Income",
            "expression": "1",
            "formatString": "#,##0",
            "lineageTag": "f6e1d663-4317-4a96-9029-11050448b7a8"
          },
          {
            "name": "Net Income Projected - Timeframe",
            "displayFolder": "Net Income",
            "expression": "SUm('ClientMatterMetrics'[NetIncomeProj])",
            "formatString": "#,##0",
            "lineageTag": "2f154bdb-89d5-42bb-843e-8ad809c7897b"
          },
          {
            "name": "Net Income Prior Year - Timeframe",
            "displayFolder": "Net Income",
            "expression": "Sum('ClientMatterMetrics'[NetIncomePY])",
            "formatString": "#,##0",
            "lineageTag": "71f15f82-03cd-4729-95c9-98c1a3884458"
          },
          {
            "name": "Fees Billed",
            "displayFolder": "Fees Billed",
            "expression": "1",
            "formatString": "#,##0",
            "lineageTag": "58a51a9f-b2b5-4fa7-9020-3d545ed04a93"
          },
          {
            "name": "Fees Billed - Timeframe",
            "displayFolder": "Fees Billed",
            "expression": "Sum('ClientMatterMetrics'[FeesBilledActual])",
            "formatString": "#,##0",
            "lineageTag": "6ad9f8e0-b5eb-4adc-b424-3b7b0f734c04"
          },
          {
            "name": "Fees Billed Budget Timeframe",
            "displayFolder": "Fees Billed",
            "expression": "1",
            "formatString": "#,##0",
            "lineageTag": "f848ff1f-86c8-4579-b7c0-b170210ce8c4"
          },
          {
            "name": "Fees Billed Projected - Timeframe",
            "displayFolder": "Fees Billed",
            "expression": "[Fees Worked Budget - Timeframe]",
            "formatString": "#,##0",
            "lineageTag": "27fcc485-133f-4f87-a5bc-d0bf8d5eae1b"
          },
          {
            "name": "Fees Billed Prior Year - Timeframe",
            "displayFolder": "Fees Billed",
            "expression": [
              "",
              "Sum('Fact Invoice Transactions'[Invoice Fee Amount])"
            ],
            "formatString": "#,##0",
            "lineageTag": "37ca1141-45cc-49fa-baf7-809435927c37"
          },
          {
            "name": "Switcher",
            "displayFolder": "Fees Billed",
            "expression": [
              "var _type = max('Number Type'[Type])",
              "var _result = Switch(_type, ",
              "\"Budget\", [Fees Billed Budget Timeframe], ",
              "\"Current\", [Fees Billed - Timeframe], ",
              "\"Projected\", [Fees Billed Projected - Timeframe], ",
              "\"Prior Year\", [Fees Billed Prior Year - Timeframe], ",
              "Blank())",
              "RETURN _result"
            ],
            "formatString": "0",
            "lineageTag": "4944fad8-55dc-4111-a997-df0a20a5eb86"
          },
          {
            "name": "Fees Worked New",
            "displayFolder": "Fees Billed",
            "expression": "SUm('Fact Proforma Transactions'[Proforma Fees Amount])",
            "formatString": "#,##0",
            "lineageTag": "63d9cfaa-b0a6-48e6-995d-54751dc8a819"
          },
          {
            "name": "Fees Collected New",
            "displayFolder": "Fees Billed",
            "expression": "Sum('Fact Receipt Transactions'[Receipt Fee Amount])",
            "formatString": "#,##0",
            "lineageTag": "c05dbd24-8d89-4c0a-9e4b-92035bad796d"
          },
          {
            "name": "Fees Billed New",
            "displayFolder": "Fees Billed",
            "expression": "Sum('Fact Invoice Transactions'[Invoice Fee Amount])",
            "formatString": "#,##0",
            "lineageTag": "c9e7749f-86ae-4ad1-a5f6-1d9c8b4d1461"
          },
          {
            "name": "Turnover Rate Ind",
            "dataCategory": "ImageUrl",
            "displayFolder": "Collections",
            "expression": [
              "",
              " Var _trendUpGood = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 3)",
              " Var _trendUpBad  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 5)",
              " Var _trendDownGood = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 6)",
              " Var _trendDownBad  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 2)",
              " Var _result = If([Turnover Rate] > 3.8, _trendUpBad, _trendDownGood)",
              " return _result"
            ],
            "lineageTag": "90bd82ec-901d-48dc-b613-c5f2d35f60ea"
          },
          {
            "name": "Total Worked - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Total Worked], 'Dim Date'[The Date])",
              "var _mtd = TOTALMTD([Total Worked], 'Dim Date'[The Date])",
              "var _py = CALCULATE([Total Worked], PREVIOUSYEAR('Dim Date'[The Date]))",
              "var _minr12 = Calculate(Min('Dim Date'[The Date]), REMOVEFILTERS('Dim Date'[The Date]), 'Dim Date'[Month Offset] = -11)",
              "var _EOM = CALCULATE(Min('Dim Date'[End of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _r12 = CALCULATE([Total Worked], DATESBETWEEN('Dim Date'[The Date], _minr12, _EOM)) ",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"Performance Year\", _py,",
              "\"R12\", _r12, ",
              " BLANK()",
              ")",
              "",
              "RETURN _result",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "4dcb4b97-f900-439a-ad6d-3abb48a32cc8"
          },
          {
            "name": "Total Worked Budget - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "var _tf = [Timeframe selected]",
              "var _bud = Sum('Fact Employment By Date'[Budgeted Fees Amount])",
              "var _ytd = TOTALYTD(_bud, 'Dim Date'[The Date])",
              "var _mtd = TOTALMTD(_bud, 'Dim Date'[The Date])",
              "var _py = CALCULATE(_bud,  REMOVEFILTERS('Dim Date'[The Date]),'Dim Date'[Year Offset] = 0)",
              "var _minr12 = Calculate(Min('Dim Date'[The Date]), REMOVEFILTERS('Dim Date'[The Date]), 'Dim Date'[Month Offset] = -11)",
              "var _EOM = CALCULATE(Min('Dim Date'[End of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _r12 = CALCULATE(_bud, DATESBETWEEN('Dim Date'[The Date], _minr12, _EOM)) ",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"Performance Year\", _py,",
              "\"R12\", _r12, ",
              " BLANK()",
              ")",
              "RETURN _result",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "8a582f82-fdea-45ca-8236-d405cc2f78d7"
          },
          {
            "name": "Total Worked Projected - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "",
              "VAR _tf = [Timeframe selected]",
              "VAR _ytd = [Total Worked Budget - Timeframe]",
              "VAR _mtd = [Total Worked Budget - Timeframe]",
              "VAR _pya =",
              "    CALCULATE (",
              "        [Total Worked],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _pyb =",
              "    CALCULATE (",
              "        [Total Worked Budget - Timeframe],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[The Date] > TODAY (),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _minr12 =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[The Date] ),",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Month Offset] = -11",
              "    )",
              "VAR _r12 =",
              "    CALCULATE (",
              "        [Total Worked],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], _minr12, TODAY () )",
              "    )",
              "VAR _EOM =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[End of the Month] ),",
              "        'Dim Date'[The Date] = TODAY ()",
              "    )",
              "VAR _budeom =",
              "    CALCULATE (",
              "        [Total Worked],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], TODAY (), _EOM )",
              "    )",
              "VAR _result =",
              "    SWITCH (",
              "        _tf,",
              "        \"YTD\", _ytd,",
              "        \"MTD\", _mtd,",
              "        \"R12\", _r12,",
              "        \"Performance Year\", _pya + _pyb,",
              "        BLANK ()",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "e53f1a7b-ca61-4aaf-a876-3e32205bf1da"
          },
          {
            "name": "Total Worked Prior Year - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "var _py = CALCULATE(",
              "    [Total Worked - Timeframe],",
              "    DATEADD('Dim Date'[The Date],-1,YEAR))",
              "RETURN _py"
            ],
            "formatString": "#,##0",
            "lineageTag": "3faecae4-f26e-4bd7-9248-1602fa42e12e"
          },
          {
            "name": "Total Worked",
            "displayFolder": "Collections",
            "expression": "Sum('Fact Timesheet'[Time Total Fees Amount])",
            "formatString": "#,##0",
            "lineageTag": "14821750-730a-487a-b9de-a72b44b770ca"
          },
          {
            "name": "Total Billed - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Total Billed], 'Dim Date'[The Date])",
              "var _mtd = TOTALMTD([Total Billed], 'Dim Date'[The Date])",
              "var _py = CALCULATE([Total Billed], PREVIOUSYEAR('Dim Date'[The Date]))",
              "var _minr12 = Calculate(Min('Dim Date'[The Date]), REMOVEFILTERS('Dim Date'[The Date]), 'Dim Date'[Month Offset] = -11)",
              "var _EOM = CALCULATE(Min('Dim Date'[End of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _r12 = CALCULATE([Total Billed], DATESBETWEEN('Dim Date'[The Date], _minr12, _EOM)) ",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"Performance Year\", _py,",
              "\"R12\", _r12, ",
              " BLANK()",
              ")",
              "",
              "RETURN _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "4f6d3c7b-1946-414a-b344-51aefa19033d"
          },
          {
            "name": "Total Billed Budget - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "var _tf = [Timeframe selected]",
              "var _ytd = TOTALYTD([Target - Fees Billed], 'Dim Date'[The Date])",
              "var _mtd = TOTALMTD([Target - Fees Billed], 'Dim Date'[The Date])",
              "var _py = CALCULATE([Target - Fees Billed],  REMOVEFILTERS('Dim Date'[The Date]),'Dim Date'[Year Offset] = 0)",
              "var _minr12 = Calculate(Min('Dim Date'[The Date]), REMOVEFILTERS('Dim Date'[The Date]), 'Dim Date'[Month Offset] = -11)",
              "var _EOM = CALCULATE(Min('Dim Date'[End of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _r12 = CALCULATE([Target - Fees Billed], DATESBETWEEN('Dim Date'[The Date], _minr12, _EOM)) ",
              "var _result = SWITCH(_tf, \"YTD\" , _ytd, ",
              "\"MTD\", _mtd, ",
              "\"Performance Year\", _py,",
              "\"R12\", _r12, ",
              " BLANK()",
              ")",
              "RETURN _result",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "abd27f6b-6c97-4145-875f-1a86d321d96e"
          },
          {
            "name": "Total Billed Projection - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              "VAR _tf = [Timeframe selected]",
              "VAR _ytd = [Total Billed Budget - Timeframe]",
              "VAR _mtd = [Total Billed Budget - Timeframe]",
              "VAR _pya =",
              "    CALCULATE (",
              "        [Total Billed],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _pyb =",
              "    CALCULATE (",
              "        [Total Billed Budget - Timeframe],",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[The Date] > TODAY (),",
              "        'Dim Date'[Year Offset] = 0",
              "    )",
              "VAR _minr12 =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[The Date] ),",
              "        REMOVEFILTERS ( 'Dim Date'[The Date] ),",
              "        'Dim Date'[Month Offset] = -11",
              "    )",
              "VAR _r12 =",
              "    CALCULATE (",
              "        [Total Billed],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], _minr12, TODAY () )",
              "    )",
              "VAR _EOM =",
              "    CALCULATE (",
              "        MIN ( 'Dim Date'[End of the Month] ),",
              "        'Dim Date'[The Date] = TODAY ()",
              "    )",
              "VAR _budeom =",
              "    CALCULATE (",
              "        [Total Billed],",
              "        DATESBETWEEN ( 'Dim Date'[The Date], TODAY (), _EOM )",
              "    )",
              "VAR _result =",
              "    SWITCH (",
              "        _tf,",
              "        \"YTD\", _ytd,",
              "        \"MTD\", _mtd,",
              "        \"R12\", _r12,",
              "        \"Performance Year\", _pya + _pyb,",
              "        BLANK ()",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatString": "#,##0",
            "lineageTag": "da263992-abbc-4766-a16e-ffc0becd4429"
          },
          {
            "name": "Total Billed Prior Year - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "var _py = CALCULATE(",
              "    [Total Billed - Timeframe],",
              "    DATEADD('Dim Date'[The Date],-1,YEAR))",
              "RETURN _py",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "e0a98c32-7202-46c9-8e72-6bcb8456b4e5"
          },
          {
            "name": "Total Billed",
            "displayFolder": "Collections",
            "expression": "Sum('Fact Invoice Transactions'[Invoice Total Amount])",
            "formatString": "#,##0",
            "lineageTag": "9dfc3c5f-6395-4103-b2b0-17d11c8143a4"
          },
          {
            "name": "Cash Collections Prior Year - Timeframe",
            "displayFolder": "Collections",
            "expression": [
              "",
              " var _py = CALCULATE(",
              "    [Cash Collections - Timeframe],",
              "    DATEADD('Dim Date'[The Date],-1,YEAR))",
              "RETURN _py",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "e03b9c91-3fa8-41f6-b314-2498e06ac06b"
          },
          {
            "name": "Outstanding Prebills > $20k",
            "displayFolder": "WIP Alerts",
            "expression": "88",
            "formatString": "#,##0",
            "lineageTag": "c688fe28-0cf4-4c35-8285-f7c735a34fcd"
          },
          {
            "name": "Missing Time Over 7 Days",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _result = Calculate([Missing Time], DATESBETWEEN('Dim Date'[The Date], _boyr, today()-7))",
              "RETURN _result"
            ],
            "formatString": "#,0",
            "lineageTag": "ff8f2d28-d873-4deb-8edd-c07979f8fa1e"
          },
          {
            "name": "Dormant Matters",
            "displayFolder": "WIP Alerts",
            "expression": "6",
            "formatString": "#,##0",
            "lineageTag": "f7f9bc00-e14f-45d0-a41f-b13c6fc12b34"
          },
          {
            "name": "Time Keepers Past Week",
            "displayFolder": "WIP Alerts",
            "expression": "124",
            "formatString": "#,##0",
            "lineageTag": "88e411cf-41dc-4da2-8a5a-86d12dea324d"
          },
          {
            "name": "AR Write-offs",
            "displayFolder": "WIP Alerts",
            "expression": "124106",
            "formatString": "#,##0",
            "lineageTag": "45dda0cf-abdd-46e3-b403-b0ef09489f76"
          },
          {
            "name": "Discounts > $25k YTD",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "//var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _result = CALCULATE(Sumx('Fact WIP Snapshot', 'Fact WIP Snapshot'[Total Fees Discount Amount]), 'Fact WIP Snapshot'[Total Fees Discount Amount] > 25000, LASTDATE('Fact WIP Snapshot'[As of Date]))",
              " RETURN _result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d22a557f-1df0-4dca-a6f8-3ae83ac1e01f"
          },
          {
            "name": "Aged Invoices > 180 Days",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "Calculate(DISTINCTCOUNT('Fact AR Snapshot'[Client Key]), 'Fact AR Snapshot'[AR Age Days] > 180, LASTDATE('Fact AR Snapshot'[As of Date]))"
            ],
            "formatString": "#,##0",
            "lineageTag": "0af287d6-b051-46b8-b269-bb55c95bdff2"
          },
          {
            "name": "AR 20k 60d",
            "displayFolder": "WIP Alerts",
            "expression": [
              "[AR KPI]",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "1133ddb3-3594-498c-9b7c-a8134027b603"
          },
          {
            "name": "WIP 20k 60d",
            "displayFolder": "WIP Alerts",
            "expression": "CALCULATE(Sum('Fact WIP Snapshot'[WIP Amount]), LASTDATE('Fact WIP Snapshot'[As of Date]))",
            "formatString": "#,##0",
            "lineageTag": "0c6ff6b0-5dad-455c-a858-490385a67b0e"
          },
          {
            "name": "AR Arrow",
            "dataCategory": "ImageUrl",
            "displayFolder": "WIP Alerts",
            "expression": [
              "var _Aug = Calculate([AR 20k 60d], 'Dim Date'[Month Abbrev] = \"Aug\")",
              "var _Jul = Calculate([AR 20k 60d], 'Dim Date'[Month Abbrev] = \"Jul\")",
              "Var _trendUpGood = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 3)",
              " Var _trendUpBad  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 4)",
              " Var _trendDownGood = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 1)",
              " Var _trendDownBad  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 2)",
              "var _check = if(_Aug > _Jul, _trendUpBad, _trendUpGood)",
              "",
              "RETURN _check"
            ],
            "lineageTag": "c1c86188-e292-43e3-b648-4c3756153eda"
          },
          {
            "name": "WIP Arrow",
            "dataCategory": "ImageUrl",
            "displayFolder": "WIP Alerts",
            "expression": [
              "var _Aug = Calculate([WIP 20k 60d], 'Dim Date'[Month Abbrev] = \"Aug\")",
              "var _Jul = Calculate([WIP 20k 60d], 'Dim Date'[Month Abbrev] = \"Jul\")",
              "Var _trendUpGood = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 3)",
              " Var _trendUpBad  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 4)",
              " Var _trendDownGood = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 1)",
              " Var _trendDownBad  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 2)",
              "var _check = if(_Aug > _Jul, _trendUpBad, _trendDownGood )",
              "RETURN _check"
            ],
            "lineageTag": "cc20ce63-df98-4173-9af9-73780073d102"
          },
          {
            "name": "Leaderboard Lawyer",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _Name = Min('Dim Employee'[Employee Display Name])",
              " var _PGname = Calculate(Min('Dim Practice Group'[Practice Group Short Description]), 'Fact AR Snapshot')",
              " var _PG = if(len(_PGname)>25, left(_PGname,25) & \"...\", _PGname)",
              "  var _Pgc = Calculate(Min('Dim Practice Group'[Practice Group Code]), 'Fact AR Snapshot')",
              " var _ext = \"x\" & Format(Min('Dim Employee'[Phone Bus Ext Number]), \"#\")",
              " var _result = TRIM(_Name  & \", \" & _ext & Unichar(10) & _PG & \" (\" & _Pgc & \")\" )",
              " return _result "
            ],
            "lineageTag": "42251029-b116-4939-914d-e2a3c4e3e6c1"
          },
          {
            "name": "AR Leaderboard Client",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _Name = SELECTEDVALUE('Dim Client'[Client Display Name])",
              "var _clt = SELECTEDVALUE('Dim Client'[Client Key])",
              "var _empkey = CALCULATE(MIN('Dim Employee'[Employee Key]), FILTER('Bridge Matter Roles', 'Bridge Matter Roles'[Client Key] = _clt && [Leaderboard AR] >0))",
              "var _Off = LOOKUPVALUE('Dim Employee'[Employee Display Name], 'Dim Employee'[Employee Key], _empkey)",
              "var _Ph = LOOKUPVALUE('Dim Employee'[Phone Bus Ext Number],'Dim Employee'[Employee Key], _empkey)",
              "var _result = trim(_Name & Unichar(10)  & _Off & \", x\" & _Ph)",
              " return _result"
            ],
            "lineageTag": "af24906d-4b55-4941-b669-2e874764d64b"
          },
          {
            "name": "AR Leaderboard Matter",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _getmatter = SELECTEDVALUE('Dim Matter'[Matter Name])",
              "var _matterkey = MIN('Dim Matter'[Matter Key])",
              "var _Name = if(len(_getmatter)>60, left(_getmatter,60) & \"...\", _getmatter)",
              "var _Mid = SELECTEDVALUE('Dim Matter'[Client Matter ID])",
              "var _getclient = Calculate(Min('Dim Client'[Client Key]) , 'Fact AR Snapshot')",
              " var _PG = LOOKUPVALUE('Dim Client'[Client Display Name], 'Dim Client'[Client Key], _getclient)",
              " var _getatty = CALCULATE(Min('Dim Employee'[Employee Key]), FILTER('Bridge Matter Roles', 'Bridge Matter Roles'[Client Key] = _getclient && [Leaderboard AR] >0))",
              " var _Att = LOOKUPVALUE('Dim Employee'[Employee Display Name], 'Dim Employee'[Employee Key], _getatty)",
              " var _Ph = LOOKUPVALUE('Dim Employee'[Phone Bus Ext Number], 'Dim Employee'[Employee Key], _getatty)",
              " var _result = TRIM(_Name & \" (\" & _Mid & \")\" & Unichar(10) & _PG  & Unichar(10) & _Att  & \", x\" & _Ph)",
              " return _result "
            ],
            "lineageTag": "f3585cf8-db98-4116-87f6-0f0af0e5889f"
          },
          {
            "name": "AR Leaderboard Practice",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _Name = if(len(Min('Dim Practice Group'[Practice Group Short Description]))>25, left(Min('Dim Practice Group'[Practice Group Short Description]),25) & \"...\", Min('Dim Practice Group'[Practice Group Short Description]))",
              " var _Pgc = Min('Dim Practice Group'[Practice Group Code])",
              " var _result = TRIM(_Name & \" (\" & _Pgc & \")\" )",
              " return _result "
            ],
            "lineageTag": "8ec24cb1-f682-48f2-bf23-ee01509dc1f5"
          },
          {
            "name": "RANK Employee AR",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard AR],,DESC,Dense)",
              "Var _RnkBottom =  RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard AR],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "7c851f5d-c0d0-43f7-ac3f-237733974bbf"
          },
          {
            "name": "Leaderboard AR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "CALCULATE([AR All Age], 'Dim Role Type'[Role Type Description] = \"Billing Attorney\", 'Dim Employee'[Employee Active] = \"Active\",'Dim Matter'[Arrangement Code] <> \"C\", 'Fact AR Snapshot'[AR Amount] > 0 )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1ea02ccc-a9af-4e3e-85a8-cf8fb3ece7e8"
          },
          {
            "name": "Leaderboard WIP",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              " CALCULATE([WIP All Ages], 'Dim Role Type'[Role Type Description] = \"Billing Attorney\", 'Dim Employee'[Employee Active] = \"Active\",'Dim Matter'[Arrangement Code] <> \"C\" )",
              "",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "522eea50-8ca3-4c34-be5a-f8027566fb75"
          },
          {
            "name": "RANK Employee WIP",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard WIP],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard WIP],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "156a4216-9e9f-4a6d-b3db-802eaab52da1"
          },
          {
            "name": "Employee Image",
            "dataCategory": "ImageUrl",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "If (HASONEVALUE('Fact Employee Photo'[Image File Name]), \"data:image/jpeg;base64, \"& ",
              "CONCATENATEX('Fact Employee Photo', 'Fact Employee Photo'[Base64 Text],,'Fact Employee Photo'[Sequence Number], ASC))"
            ],
            "lineageTag": "fb5d58a6-94a9-481b-963b-f4f8e01ca975"
          },
          {
            "name": "AR Days",
            "displayFolder": "AR",
            "expression": "[Avg Days in AR]",
            "formatString": "0.0",
            "lineageTag": "18d816a9-3523-48fe-a907-0f0a8f4957a5"
          },
          {
            "name": "WIP Days",
            "displayFolder": "AR",
            "expression": "[Avg Days in WIP]",
            "formatString": "0.0",
            "lineageTag": "ae36d8b7-3f9f-4608-88df-65ba2142b3aa"
          },
          {
            "name": "AR All Age",
            "displayFolder": "AR",
            "expression": "Calculate(sum('Fact AR Snapshot'[AR Amount]), LASTDATE('Fact AR Snapshot'[As of Date]))",
            "formatString": "#,##0",
            "lineageTag": "a9773849-5a34-4fed-979d-c865cb9b0008"
          },
          {
            "name": "WIP All Ages",
            "displayFolder": "AR",
            "expression": "CALCULATE(Sum('Fact WIP Snapshot'[WIP Amount]), LASTDATE('Fact WIP Snapshot'[As of Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "eb55a1f2-6d57-48ec-8341-4614070efb20"
          },
          {
            "name": "RANK Client AR",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Client'[Client Key]), [Leaderboard AR],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Client'[Client Key]), [Leaderboard AR],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "385cae56-736e-4434-9549-0e6acb6c305a"
          },
          {
            "name": "RANK Practice AR",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Practice Group'[Practice Group ID]), [Leaderboard AR],,DESC,Dense)",
              "Var _RnkBottom =RANKX(ALLSELECTED('Dim Practice Group'[Practice Group ID]), [Leaderboard AR],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk",
              ""
            ],
            "formatString": "0",
            "lineageTag": "943450ea-81fb-484f-b333-16a5087de556"
          },
          {
            "name": "RANK Matter AR",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Matter'[Matter Key]), [Leaderboard AR],,DESC,Dense)",
              "Var _RnkBottom =RANKX(ALLSELECTED('Dim Matter'[Matter Key]), [Leaderboard AR],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk",
              ""
            ],
            "formatString": "0",
            "lineageTag": "986d086c-1d15-4a28-9011-714f26d78784"
          },
          {
            "name": "RANK Matter WIP",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop =",
              "RANKX(ALLSELECTED('Dim Matter'[Matter Key]), [Leaderboard WIP],,DESC,Dense)",
              "Var _RnkBottom =",
              "RANKX(ALLSELECTED('Dim Matter'[Matter Key]), [Leaderboard WIP],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk",
              ""
            ],
            "formatString": "0",
            "lineageTag": "925942e7-68a8-4564-965a-bc841b70bfe5"
          },
          {
            "name": "RANK Client WIP",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Client'[Client Key]), [Leaderboard WIP],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Client'[Client Key]), [Leaderboard WIP],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "#,0",
            "lineageTag": "b0075174-771b-465b-9578-c37af0f2a094"
          },
          {
            "name": "RANK Practice WIP",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Practice Group'[Practice Group ID]), [WIP All Ages],,DESC,Dense)",
              "Var _RnkBottom =RANKX(ALLSELECTED('Dim Practice Group'[Practice Group ID]), [WIP All Ages],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5e551c63-08ac-4827-87b5-01535e7dad60"
          },
          {
            "name": "Pro Forma Target Status",
            "displayFolder": "WIP Alerts",
            "expression": "\"+$639k\"",
            "lineageTag": "12ce370c-9bc2-4e3c-9449-68c0cb7f5e2c"
          },
          {
            "name": "Avg Days in WIP",
            "displayFolder": "WIP Alerts",
            "expression": [
              "CALCULATE(Average('Fact WIP Snapshot'[WIP Age Days]), LASTDATE('Fact WIP Snapshot'[As of Date])",
              ")"
            ],
            "lineageTag": "675b9c40-3550-42b7-a982-c397e81bb1b5"
          },
          {
            "name": "Avg Days in AR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": [
              "CALCULATE(SUM('Fact AR Snapshot'[Weighted AR Days]), LASTDATE('Fact AR Snapshot'[As of Date])",
              ")"
            ],
            "lineageTag": "3ce4af08-4987-4217-a3a3-5d731a09193b"
          },
          {
            "name": "Write-downs arrow",
            "dataCategory": "ImageUrl",
            "displayFolder": "WIP Alerts",
            "expression": [
              "Var _UpRedArrow  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 7)",
              "RETURN _UpRedArrow"
            ],
            "lineageTag": "5338e113-3762-496a-98c3-abcbfd6423bf"
          },
          {
            "name": "Aged Invoice Arrow",
            "dataCategory": "ImageUrl",
            "displayFolder": "WIP Alerts",
            "expression": [
              "Var _UpYellowArrow  = CALCULATE(Max('Trend Arrows'[Image]), 'Trend Arrows'[Index] = 8)",
              "RETURN _UpYellowArrow"
            ],
            "lineageTag": "066f9b4a-bbb8-4198-8e0a-aff1978c7d53"
          },
          {
            "name": "Discounts trend text",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _num = [Discounts Diff Pct]",
              "var _numtext = if(_num <> 0, Format(abs(_num), \"#%\"), \"No change\")",
              "var _arrow = SWITCH(TRUE(),_num> 0, \" \",",
              "_num <0,\" \", \"\")",
              "var _trend = _arrow & _numtext & \" since \"",
              "var _dt = format(EOMONTH(TODAY(),-1),\"dd MMM yy\")",
              "var _result = CONCATENATE(_trend, _dt)",
              "return _result"
            ],
            "lineageTag": "6166f324-d0e9-4a91-a68a-abe0a62c6047"
          },
          {
            "name": "Aged Invoice trend text",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "",
              "var _num = [Aged Invoice Diff Pct]",
              "var _numtext = if(_num <> 0, Format(abs(_num), \"#%\"), \"No change\")",
              "var _arrow = SWITCH(TRUE(),_num> 0, \" \",",
              "_num <0,\" \", \"\")",
              "var _trend = _arrow & _numtext & \" since \"",
              "var _dt = format(EOMONTH(TODAY(),-1),\"dd MMM yy\")",
              "var _result = CONCATENATE(_trend, _dt)",
              "return _result"
            ],
            "lineageTag": "1614a519-8faf-4484-b163-7df259f8f84a"
          },
          {
            "name": "RANK Employee URPFA",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Amt Atty],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Amt Atty],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "b6c9a267-c75a-4199-9f74-e33082685e44"
          },
          {
            "name": "RANK Employee URPFN",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Number Atty],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Number Atty],,ASC,Dense)",
              "",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "f12f045c-c6af-4293-8daa-34d2d5f073c9"
          },
          {
            "name": "Fee Writedowns",
            "displayFolder": "WIP Alerts",
            "expression": "CALCULATE(Sum('Fact WIP Snapshot'[Fee Write Up Write Down Amount]), LASTDATE('Fact WIP Snapshot'[As of Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "55358ee1-1fe9-4d20-8be9-030ec2871a51"
          },
          {
            "name": "Hard Cost Write Downs",
            "displayFolder": "WIP Alerts",
            "expression": "CALCULATE(Sum('Fact WIP Snapshot'[Hard Disbursed Write Down Amount]), LASTDATE('Fact WIP Snapshot'[As of Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c187d6c1-adef-49b4-93cc-eeb9158b4631"
          },
          {
            "name": "Time Worked",
            "displayFolder": "WIP Alerts",
            "expression": "Sum('Fact Timesheet'[Time Total Hours Number])",
            "formatString": "0",
            "lineageTag": "595dac6a-d64b-49a4-b81a-279b493bf922"
          },
          {
            "name": "Time Budgeted",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": "Sum('Fact Employment By Date'[Budgeted Hours Amount])",
            "lineageTag": "099669c7-70d9-4b12-85e9-e97df5e4a575"
          },
          {
            "name": "Missing Time",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _tbl = ADDCOLUMNS(",
              "    SUMMARIZE( 'Fact Employment By Date', 'Dim Employee'[Employee ID], 'Dim Date'[The Date]),",
              "    \"_budgeted\", CALCULATE( [Time Budgeted]), \"_worked\", CALCULATE([Time Worked]), \"_missing\", if(CALCULATE( [Time Budgeted]) < CALCULATE([Time Worked]), 0,CALCULATE( [Time Budgeted]) - CALCULATE([Time Worked]))",
              ")",
              "var _missingttl = Sumx(_tbl, [_missing])",
              "var _result = _missingttl",
              "return _result"
            ],
            "lineageTag": "3bf89bd2-5c15-40ae-8558-f215d9e94289"
          },
          {
            "name": "AR KPI",
            "displayFolder": "AR",
            "expression": [
              "",
              "",
              "var _dt = CALCULATE(Max('Fact AR Snapshot'[As of Date]), 'Dim Date'[The Date] <= Today())",
              "var _filtereddays =  CALCULATE(Sumx('Fact AR Snapshot', [AR All Age]),  'Fact AR Snapshot'[AR Age Days] > 60, 'Fact AR Snapshot'[AR Amount] > 20000, LastDate('Fact AR Snapshot'[As of Date]))",
              "return _filtereddays",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d51a251f-3fa3-4754-9990-2b5f3ec82a86"
          },
          {
            "name": "Invoice AR",
            "displayFolder": "AR",
            "expression": [
              "",
              " Calculate(sum('Fact Invoice Transactions'[Invoice Balance Amount]), 'Dim Invoice'[Invoice Paid Flag] = FALSE())",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ce283cb9-b5a2-4b11-b9db-c71a2a5b89da"
          },
          {
            "name": "Proforma Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": "Sum('Fact Proforma Transactions'[Proforma Total Amount])",
            "lineageTag": "31f9170a-aeb8-410c-b200-fda0a0301f3d"
          },
          {
            "name": "Proforma Fees",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": "Sum('Fact Proforma Transactions'[Proforma Fees Amount])",
            "lineageTag": "fd100b01-36d3-4154-8dcb-bd69c73d4a41"
          },
          {
            "name": "First Date of Quarter",
            "expression": [
              "",
              "  Calculate(Min('Dim Date'[Start of Quarter]), 'Dim Date'[The Date] = TODAY())"
            ],
            "formatString": "Short Date",
            "lineageTag": "0a438a66-5af3-489a-980f-9420faaefbea"
          },
          {
            "name": "Title - Finalized Proformas",
            "expression": [
              "",
              "var _str = \"Finalized Proformas Generated On/After \" ",
              "var _dt = FORMAT([First of Month], \"d MMMM YYYY\")",
              "var _result = _str & _dt",
              "RETURN _result"
            ],
            "lineageTag": "ce2d5492-3066-4fbf-8d3a-10a8e2030575"
          },
          {
            "name": "Proforma Count",
            "displayFolder": "WIP Alerts",
            "expression": "COUNTROWS('Fact Proforma Transactions')",
            "formatString": "0",
            "lineageTag": "f90d1ba1-8a01-4aed-8611-1b04da00c9a1"
          },
          {
            "name": "Title - Unbillty Atty Proformas",
            "expression": [
              "",
              "var _str = \"Unbilled - Attorney Proformas Generated On/After \"",
              "var _dt = FORMAT([First of Month], \"d MMMM YYYY\")",
              "var _result = _str & _dt",
              "RETURN _result"
            ],
            "lineageTag": "4b1e6387-91f0-4990-a4ab-9db23974e98a"
          },
          {
            "name": "Avg Days to Bill",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _dt = [First of Month]",
              "var _result = Calculate(AVERAGE('Fact Proforma Transactions'[Total Days to Bill]), 'Fact Proforma Transactions'[Proforma Date] >= _dt)",
              "RETURN _result"
            ],
            "lineageTag": "9c0be0fa-0123-41ba-b9cd-3455622d2c09"
          },
          {
            "name": "Avg Acct Days to Bill",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _dt = [First of Month]",
              "var _result = Calculate(AVERAGE('Fact Proforma Transactions'[Accounting Days To Bill Number]), 'Fact Proforma Transactions'[Proforma Date] >= _dt)",
              "RETURN _result"
            ],
            "lineageTag": "4ffcdf49-bb10-409c-a880-263979998763"
          },
          {
            "name": "Target - Days in WIP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(MAX('Fact Firm Target Snapshot'[Target Amount]), 'Dim Firm Target'[Target Description] = \"Days in WIP\")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "2547b5ed-69d3-4865-9627-47b96f930051"
          },
          {
            "name": "Target - Days in AR",
            "expression": [
              "",
              "CALCULATE(MAX('Fact Firm Target Snapshot'[Target Amount]), 'Dim Firm Target'[Target Description] = \"Days in AR\")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f8feb95b-38f8-4e66-9987-228e127a2dfd"
          },
          {
            "name": "WIP KPI",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _amt = [WIP All Ages]",
              "var _dt = CALCULATE(Max('Fact WIP Snapshot'[As of Date]), 'Fact WIP Snapshot'[As of Date] <= Today())",
              "var _filtereddays =  CALCULATE(Sumx('Fact WIP Snapshot', [WIP All Ages]), 'Fact WIP Snapshot'[WIP Age Days] > 60, 'Fact WIP Snapshot'[WIP Amount] > 20000, 'Dim Date'[The Date] = _dt)",
              "return _filtereddays"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "654a5792-97c8-46cf-a276-ec7dc681a834"
          },
          {
            "name": "WIP Leaderboard Client",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _Name = SELECTEDVALUE('Dim Client'[Client Display Name])",
              "var _clt = SELECTEDVALUE('Dim Client'[Client Key])",
              "var _getatty = CALCULATE(Min('Dim Employee'[Employee Key]), FILTER('Bridge Matter Roles', 'Bridge Matter Roles'[Client Key] = _clt && [WIP All Ages] >0))",
              "var _Off = LOOKUPVALUE('Dim Employee'[Employee Display Name], 'Dim Employee'[Employee Key], _getatty)",
              "var _Ph = LOOKUPVALUE('Dim Employee'[Phone Bus Ext Number],'Dim Employee'[Employee Key], _getatty)",
              "var _result = TRIM(_Name & Unichar(10)  & _Off & \", x\" & _Ph)",
              " return _result"
            ],
            "lineageTag": "63381387-c395-4a63-9d5c-09d9612ae35b"
          },
          {
            "name": "URPF Client",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _Name = Min('Dim Client'[Client Name])",
              " var _PG = Min('Dim Client'[Firm Industry Description])",
              " var _Off = CALCULATE(Min('Dim Employee'[Pref LFMI Name]), 'Fact Proforma Transactions')",
              " var _Ph = CALCULATE(MIN('Dim Employee'[Phone Bus Ext Number]), 'Fact Proforma Transactions')",
              " var _result = TRIM(_Name & Unichar(10) & _PG & Unichar(10) & _Off & \", x\" & _Ph)",
              " return _result "
            ],
            "lineageTag": "26a2f1ba-fd78-44ab-a031-37e520f2fd3b"
          },
          {
            "name": "WIP Leaderboard Matter",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _getmatter = SELECTEDVALUE('Dim Matter'[Matter Name])",
              "var _matterkey = MIN('Dim Matter'[Matter Key])",
              "var _Name = if(len(_getmatter)>60, left(_getmatter,60) & \"...\", _getmatter)",
              "var _Mid = SELECTEDVALUE('Dim Matter'[Client Matter ID])",
              "var _getclient = Calculate(Min('Dim Client'[Client Key]) , 'Fact WIP Snapshot')",
              " var _PG = LOOKUPVALUE('Dim Client'[Client Display Name], 'Dim Client'[Client Key], _getclient)",
              " var _getatty = CALCULATE(Min('Dim Employee'[Employee Key]), FILTER('Bridge Matter Roles', 'Bridge Matter Roles'[Client Key] = _getclient && [WIP All Ages] >0))",
              " var _Att = LOOKUPVALUE('Dim Employee'[Employee Display Name], 'Dim Employee'[Employee Key], _getatty)",
              " var _Ph = LOOKUPVALUE('Dim Employee'[Phone Bus Ext Number], 'Dim Employee'[Employee Key], _getatty)",
              " var _result = TRIM(_Name & \" (\" & _Mid & \")\" & Unichar(10) & _PG  & Unichar(10) & _Att  & \", x\" & _Ph)",
              " return _result "
            ],
            "lineageTag": "0f6d32f5-3457-43ae-a083-e2a68d6bd22a"
          },
          {
            "name": "WIP Leaderboard Practice",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _getpg = SELECTEDVALUE('Dim Practice Group'[Practice Group Short Description])",
              "var _Name = if(len(_getpg)>30, left(_getpg,30) & \"...\", _getpg)",
              " var _Ldr = CALCULATE(Min('Dim Employee'[Pref LFMI Name]), 'Fact WIP Snapshot')",
              " var _Ph = CALCULATE(MIN('Dim Employee'[Phone Bus Ext Number]), 'Fact WIP Snapshot')",
              " var _Pgc = Min('Dim Practice Group'[Practice Group Code])",
              " var _result = TRIM(_Name & \" (\" & _Pgc & \")\" )",
              " return _result "
            ],
            "lineageTag": "a1f48a4a-c0e4-46a3-9bb0-12ca3b180701"
          },
          {
            "name": "Last Date Prior Month",
            "expression": [
              "",
              "Calculate(Min('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY()) -1 "
            ],
            "formatString": "Short Date",
            "lineageTag": "8e5b6587-9305-4a4e-89a2-516982d681c4"
          },
          {
            "name": "Target - Fees Billed",
            "expression": [
              "",
              "CALCULATE(MAX('Fact Firm Target Snapshot'[Target Amount]), 'Dim Firm Target'[Target Description] = \"Fees Billed\")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "af7df32c-6a14-4700-a82d-73ebcdf3180f"
          },
          {
            "name": "Target - Fees Collected",
            "expression": [
              "",
              "CALCULATE(MAX('Fact Firm Target Snapshot'[Target Amount]), 'Dim Firm Target'[Target Description] = \"Fees Collected\")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "22c78a0b-ba15-49b4-af6a-01c42eb05439"
          },
          {
            "name": "Discounts Diff Pct",
            "expression": [
              "",
              "var _bomo = CALCULATE(Max('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _pm = CALCULATE(Sumx('Fact Invoice Transactions', 'Fact Invoice Transactions'[Discount]), 'Fact Invoice Transactions'[Discount] > 25000, DATESBETWEEN('Dim Date'[The Date], _boyr, _bomo - 1))",
              "var _td = CALCULATE(Sumx('Fact Invoice Transactions', 'Fact Invoice Transactions'[Discount]), 'Fact Invoice Transactions'[Discount] > 25000, DATESBETWEEN('Dim Date'[The Date], _boyr, TODAY()))",
              "var _result = divide(_td - _pm, _pm)",
              " RETURN _result"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e85c9a4d-161a-460c-9483-b6a30cd03c31"
          },
          {
            "name": "YTD AVG Days WIP",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              " var _result = CALCULATE([Avg Days in WIP], DATESBETWEEN('Dim Date'[The Date], _boyr, today()))",
              " RETURN _result"
            ],
            "formatString": "0",
            "lineageTag": "eecc3937-a432-47d5-b3a0-ebf1bdb90a1b"
          },
          {
            "name": "YTD AVG Days AR",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              " var _result = CALCULATE([Avg Days in AR], DATESBETWEEN('Dim Date'[The Date], _boyr, today()))",
              " RETURN _result"
            ],
            "formatString": "0",
            "lineageTag": "42d49839-ff9d-4907-887e-ef7b00ca6f02"
          },
          {
            "name": "YTD Aged Invoices > 180",
            "expression": [
              "",
              "",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              " var _result = CALCULATE([Aged Invoices > 180 Days], DATESBETWEEN('Dim Date'[The Date], _boyr, today()))",
              " RETURN _result"
            ],
            "formatString": "#,0",
            "lineageTag": "41c484d3-ffbf-4ba0-94d9-e203673e02ca"
          },
          {
            "name": "Discount SVG",
            "expression": [
              "",
              "Var _pct = [Discounts Diff Pct]",
              "Var _trendtext = [Discounts trend text]",
              "var _badcolor = \"#A1343C\"",
              "var _goodcolor = \"#3A9256\"",
              "var _color = if(_pct > 0,_badcolor, _goodcolor)",
              "var _style = \"<style>",
              "    .txt {",
              "      font-size: 12;",
              "      font-family: Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif;",
              "      fill: \" & _color & \"",
              "    }</style>\"",
              "",
              "VAR _defs = \"    <text x='0' y='0' dy='0' class='txt'>",
              "        <tspan x='0' dy='.9em'>\" & _trendtext & \"</tspan>",
              "    </text>\"",
              "Var _height = 50",
              "Var _width = 200",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _svgEnd",
              "RETURN _result",
              ""
            ],
            "lineageTag": "c6cf49bc-fc37-43ba-b838-aa44355c0bed"
          },
          {
            "name": "Blank",
            "expression": "Blank()",
            "formatString": "0",
            "lineageTag": "987ec271-f778-4752-aeee-61542c358ee9"
          },
          {
            "name": "Aged Invoice Diff Pct",
            "expression": [
              "",
              "var _bomo = CALCULATE(Max('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _pm = ",
              "Calculate(DISTINCTCOUNT('Fact AR Snapshot'[Client Key]), 'Fact AR Snapshot'[AR Age Days] > 180, LASTDATE('Fact AR Snapshot'[As of Date]), 'Dim Date'[The Date] = _bomo-1)",
              "var _td = ",
              "Calculate(DISTINCTCOUNT('Fact AR Snapshot'[Client Key]), 'Fact AR Snapshot'[AR Age Days] > 180, LASTDATE('Fact AR Snapshot'[As of Date]), DATESBETWEEN('Dim Date'[The Date], _boyr, TODAY()))",
              "var _result = divide(_td - _pm, _pm)",
              " RETURN _pm"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f104a1af-5538-4348-9361-1d8de6d4e76d"
          },
          {
            "name": "Invoice Age SVG",
            "expression": [
              "",
              "Var _pct = [Aged Invoice Diff Pct]",
              "Var _trendtext = [Aged Invoice trend text]",
              "var _badcolor = \"#A1343C\"",
              "var _goodcolor = \"#3A9256\"",
              "var _color = if(_pct > 0,_badcolor, _goodcolor)",
              "var _style = \"<style>",
              "    .txt {",
              "      font-size: 12;",
              "      font-family: Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif;",
              "      fill: \" & _color & \"",
              "    }</style>\"",
              "",
              "VAR _defs = \"    <text x='0' y='0' dy='0' class='txt'>",
              "        <tspan x='0' dy='.9em'>\" & _trendtext & \"</tspan>",
              "    </text>\"",
              "Var _height = 50",
              "Var _width = 200",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _svgEnd",
              "RETURN _result",
              ""
            ],
            "lineageTag": "f070d4c8-6a4f-48a9-81fe-4e54ba03702a"
          },
          {
            "name": "Fee Writedowns Diff Pct",
            "expression": [
              "",
              "var _bomo = CALCULATE(Max('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _pm = CALCULATE([Fee Writedowns], DATESBETWEEN('Dim Date'[The Date], _boyr, _bomo - 1))",
              "var _td = CALCULATE([Fee Writedowns], DATESBETWEEN('Dim Date'[The Date], _boyr, TODAY()))",
              "var _result = divide(_td - _pm, _pm)",
              " RETURN _result"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c137f8af-e72e-44b5-889c-8313ef5edec8"
          },
          {
            "name": "Fee Writedowns Trend Text",
            "expression": [
              "var _num = [Fee Writedowns Diff Pct]",
              "var _numtext = if(_num <> 0, Format(abs(_num), \"#%\"), \"No change\")",
              "var _arrow = SWITCH(TRUE(),_num> 0, \" \",",
              "_num <0,\" \", \"\")",
              "var _trend = _arrow & _numtext & \" since \"",
              "var _dt = format(EOMONTH(TODAY(),-1),\"dd MMM yy\")",
              "var _result = CONCATENATE(_trend, _dt)",
              "return _result"
            ],
            "lineageTag": "1ace99bb-69f5-49ee-9052-e089c6174486"
          },
          {
            "name": "Fee Writedowns SVG",
            "expression": [
              "",
              "Var _pct = [Fee Writedowns Diff Pct]",
              "Var _trendtext = [Fee Writedowns Trend Text]",
              "var _badcolor = \"#A1343C\"",
              "var _goodcolor = \"#3A9256\"",
              "var _color = if(_pct > 0,_badcolor, _goodcolor)",
              "var _style = \"<style>",
              "    .txt {",
              "      font-size: 12;",
              "      font-family: Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif;",
              "      fill: \" & _color & \"",
              "    }</style>\"",
              "",
              "VAR _defs = \"    <text x='0' y='0' dy='0' class='txt'>",
              "        <tspan x='0' dy='.9em'>\" & _trendtext & \"</tspan>",
              "    </text>\"",
              "Var _height = 50",
              "Var _width = 200",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _svgEnd",
              "RETURN _result",
              ""
            ],
            "lineageTag": "876a663e-24b9-46e8-849d-79c2525a1829"
          },
          {
            "name": "Hard Cost Diff Pct",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var _bomo = CALCULATE(Max('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY())",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _pm = CALCULATE([Hard Cost Write Downs], DATESBETWEEN('Dim Date'[The Date], _boyr, _bomo - 1))",
              "var _td = CALCULATE([Hard Cost Write Downs], DATESBETWEEN('Dim Date'[The Date], _boyr, TODAY()))",
              "var _result = divide(_td - _pm, _pm)",
              " RETURN _result"
            ],
            "lineageTag": "fa0d8960-8c06-4900-b70d-13fe3c944f81"
          },
          {
            "name": "Hard Cost Trend Text",
            "expression": [
              "var _num = [Hard Cost Diff Pct]",
              "var _numtext = if(_num <> 0, Format(abs(_num), \"#%\"), \"No change\")",
              "var _arrow = SWITCH(TRUE(),_num> 0, \" \",",
              "_num <0,\" \", \"\")",
              "var _trend = _arrow & _numtext & \" since \"",
              "var _dt = format(EOMONTH(TODAY(),-1),\"dd MMM yy\")",
              "var _result = CONCATENATE(_trend, _dt)",
              "return _result"
            ],
            "lineageTag": "0b259aaa-ab24-470c-9fbe-22789c251036"
          },
          {
            "name": "Hard Cost SVG",
            "expression": [
              "",
              "Var _pct = [Hard Cost Diff Pct]",
              "Var _trendtext = [Hard Cost Trend Text]",
              "var _badcolor = \"#A1343C\"",
              "var _goodcolor = \"#3A9256\"",
              "var _color = if(_pct > 0,_badcolor, _goodcolor)",
              "var _style = \"<style>",
              "    .txt {",
              "      font-size: 12;",
              "      font-family: Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif;",
              "      fill: \" & _color & \"",
              "    }</style>\"",
              "",
              "VAR _defs = \"    <text x='0' y='0' dy='0' class='txt'>",
              "        <tspan x='0' dy='.9em'>\" & _trendtext & \"</tspan>",
              "    </text>\"",
              "Var _height = 50",
              "Var _width = 200",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _svgEnd",
              "RETURN _result",
              ""
            ],
            "lineageTag": "3f022dac-d806-4b4d-b5c9-b9af7e21d4cf"
          },
          {
            "name": "WIP KPI Diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var _bomo = CALCULATE(Max('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY())",
              "",
              "var _amt = [WIP All Ages]",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _dt = CALCULATE(Max('Fact WIP Snapshot'[As of Date]), 'Fact WIP Snapshot'[As of Date] <= Today())",
              "var _td =  CALCULATE(Sumx('Fact WIP Snapshot', [WIP All Ages]), 'Fact WIP Snapshot'[WIP Age Days] > 60, 'Fact WIP Snapshot'[WIP Amount] > 20000, 'Dim Date'[The Date] = _dt)",
              "var _pm = CALCULATE(Sumx('Fact WIP Snapshot', [WIP All Ages]), 'Fact WIP Snapshot'[WIP Age Days] > 60, 'Fact WIP Snapshot'[WIP Amount] > 20000, 'Dim Date'[The Date] = (_bomo-1))",
              "var _result = _td - _pm",
              " RETURN _result"
            ],
            "lineageTag": "6904217f-e471-4310-b271-deb22de92911"
          },
          {
            "name": "WIP KPI Chart",
            "displayFolder": "WIP Alerts",
            "expression": [
              "",
              "var _amt = [WIP All Ages]",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _dt = CALCULATE(Max('Fact WIP Snapshot'[As of Date]), 'Fact WIP Snapshot'[As of Date] <= Today())",
              "var _filtereddays =  CALCULATE(Sumx('Fact WIP Snapshot', [WIP All Ages]), 'Fact WIP Snapshot'[WIP Age Days] > 60, 'Fact WIP Snapshot'[WIP Amount] > 20000)",
              "",
              "return _filtereddays"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "82c1143d-7239-4a4e-871e-731cd1aefe5c"
          },
          {
            "name": "WIP KPI SVG",
            "expression": [
              "",
              "",
              "Var _diff = [WIP KPI Diff]",
              "Var _trendtext = [WIP KPI Trend Text]",
              "var _badcolor = \"#A1343C\"",
              "var _goodcolor = \"#3A9256\"",
              "var _color = if(_diff > 0,_badcolor, _goodcolor)",
              "var _style = \"<style>",
              "    .txt {",
              "      font-size: 12;",
              "      font-family: Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif;",
              "      fill: \" & _color & \"",
              "    }</style>\"",
              "",
              "VAR _defs = \"    <text x='0' y='0' dy='0' class='txt'>",
              "        <tspan x='0' dy='.9em'>\" & _trendtext & \"</tspan>",
              "    </text>\"",
              "Var _height = 50",
              "Var _width = 210",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _svgEnd",
              "RETURN _result",
              ""
            ],
            "lineageTag": "9b5e49c9-5a02-49b2-85d1-1c55a6a0cbef"
          },
          {
            "name": "WIP KPI Trend Text",
            "expression": [
              "var _num = [WIP KPI]",
              "var _numtext = if(_num <> 0, Format(abs(_num), \"#,###\"), \"No change\")",
              "var _arrow = SWITCH(TRUE(),_num> 0, \" \",",
              "_num <0,\" \", \"\")",
              "var _trend = _arrow & _numtext & \" since \"",
              "var _dt = format(EOMONTH(TODAY(),-1),\"dd MMM yy\")",
              "var _result = CONCATENATE(_trend, _dt)",
              "return _result"
            ],
            "lineageTag": "b4620feb-e545-457c-947d-952c50c60569"
          },
          {
            "name": "AR KPI Chart",
            "expression": [
              "",
              "var _amt = sum('Fact AR Snapshot'[AR Amount])",
              "var _filtereddays =  CALCULATE(Sumx('Fact AR Snapshot',[AR All Age]), 'Fact AR Snapshot'[AR Age Days] > 60, 'Fact AR Snapshot'[AR Amount] > 20000, LASTDATE('Fact AR Snapshot'[As of Date]))",
              "",
              "return _filtereddays",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6a403571-4443-470c-8518-f01c336b4b1e"
          },
          {
            "name": "AR KPI DIff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var _bomo = CALCULATE(Max('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY())",
              "",
              "var _amt = [AR All Age]",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _dt = CALCULATE(Max('Fact AR Snapshot'[As of Date]), 'Fact AR Snapshot'[As of Date] <= Today())",
              "var _td =  CALCULATE(Sumx('Fact AR Snapshot', [AR All Age]), 'Fact AR Snapshot'[AR Age Days] > 60, 'Fact AR Snapshot'[AR Amount] > 20000, 'Dim Date'[The Date] = _dt)",
              "var _pm = CALCULATE(Sumx('Fact AR Snapshot', [AR All Age]), 'Fact AR Snapshot'[AR Age Days] > 60, 'Fact AR Snapshot'[AR Amount] > 20000, 'Dim Date'[The Date] = (_bomo-1))",
              "var _result = _td - _pm",
              " RETURN _result"
            ],
            "lineageTag": "73f935ca-b0ee-4341-adb5-a3c35fd24e4d"
          },
          {
            "name": "AR KPI SVG",
            "expression": [
              "",
              "",
              "Var _diff = [AR KPI Diff]",
              "Var _trendtext = [AR KPI Trend Text]",
              "var _badcolor = \"#A1343C\"",
              "var _goodcolor = \"#3A9256\"",
              "var _color = if(_diff > 0,_badcolor, _goodcolor)",
              "var _style = \"<style>",
              "    .txt {",
              "      font-size: 12;",
              "      font-family: Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif;",
              "      fill: \" & _color & \"",
              "    }</style>\"",
              "",
              "VAR _defs = \"    <text x='0' y='0' dy='0' class='txt'>",
              "        <tspan x='0' dy='.9em'>\" & _trendtext & \"</tspan>",
              "    </text>\"",
              "Var _height = 50",
              "Var _width = 210",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _svgEnd",
              "RETURN _result",
              ""
            ],
            "lineageTag": "d6bcc9b7-5fc0-41c2-972d-0fcc7aa37f03"
          },
          {
            "name": "AR KPI Trend Text",
            "expression": [
              "var _num = [AR KPI DIff]",
              "var _numtext = if(_num <> 0, Format(abs(_num), \"#,###\"), \"No change\")",
              "var _arrow = SWITCH(TRUE(),_num> 0, \" \",",
              "_num <0,\" \", \"\")",
              "var _trend = _arrow & _numtext & \" since \"",
              "var _dt = format(EOMONTH(TODAY(),-1),\"dd MMM yy\")",
              "var _result = CONCATENATE(_trend, _dt)",
              "return _result"
            ],
            "lineageTag": "d4ec216f-2584-4bdc-a216-6003db7d1a02"
          },
          {
            "name": "Fee Writedowns YTD",
            "expression": [
              "",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _result = CALCULATE([Fee Writedowns], DATESBETWEEN('Dim Date'[The Date], _boyr, today()))",
              " RETURN _result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4601e16e-3c5a-4c94-a2d4-240ef2f8f0c7"
          },
          {
            "name": "YTD Hard Cost Writedowns",
            "expression": [
              "",
              "var _boyr = CALCULATE(Max('Dim Date'[Start of Year]), 'Dim Date'[The Date] = TODAY())",
              "var _result = CALCULATE([Hard Cost Write Downs], DATESBETWEEN('Dim Date'[The Date], _boyr, today()))",
              "RETURN _result "
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1ac8f2d7-0755-4d2f-9e66-9174ed70429a"
          },
          {
            "name": "Proforma Amt After Date",
            "expression": [
              "",
              "var _dt = [First of Month]",
              "var _result = CALCULATE([Proforma Amount], FILTER('Fact Proforma Transactions','Fact Proforma Transactions'[Proforma Date]>= _dt))",
              "RETURN _result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a0d9b8c0-a673-47d8-b7f4-065e4b9d1786"
          },
          {
            "name": "First of Month",
            "expression": [
              "",
              "Var _first = Calculate(Min('Dim Date'[Start of the Month]), 'Dim Date'[The Date] = TODAY() ) ",
              "Var _LM = EDATE(_first,-1)",
              "Var _third = CALCULATE(MIN('Dim Date'[The Date]), 'Dim Date'[Year Offset] = 0, 'Dim Date'[Month Offset] = 0, 'Dim Date'[Day of Month] >=3, NOT('Dim Date'[Day of Week] in {1,7}))",
              "Var _Result = if(TODAY()>= _third, _first, _LM)",
              "RETURN _Result"
            ],
            "formatString": "General Date",
            "lineageTag": "52b566a5-7c31-4e1a-a7c2-578fd6952f9a"
          },
          {
            "name": "Proforma Fees After Date",
            "expression": [
              "",
              "var _dt = [First of Month]",
              "var _result = CALCULATE([Proforma Fees], Filter('Fact Proforma Transactions','Fact Proforma Transactions'[Proforma Date]>= _dt))",
              "RETURN _result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7f299d05-b30f-4953-8471-82e36a5e62d9"
          },
          {
            "name": "Title - Unbilled Acct Proformas",
            "expression": [
              "",
              "var _str = \"Unbilled - Accounting Proformas Generated On/After \"",
              "var _dt = FORMAT([First of Month], \"d MMMM YYYY\")",
              "var _result = _str & _dt",
              "RETURN _result"
            ],
            "lineageTag": "97faa79c-2893-4f02-9bad-4ed3159c8623"
          },
          {
            "name": "Proforma Count After Date",
            "expression": [
              "",
              "var _dt = [First of Month]",
              "var _result = CALCULATE(COUNTROWS('Fact Proforma Transactions'), 'Fact Proforma Transactions'[Proforma Date]>= _dt)",
              "RETURN _result"
            ],
            "formatString": "#,0",
            "lineageTag": "cfef70c8-d9d5-409d-a712-bde35017eb45"
          },
          {
            "name": "Test Ph ln",
            "expression": [
              "",
              "var ph = SELECTEDVALUE('Dim Employee'[Phone Bus Ext Number])",
              "var len = len(ph)",
              "return len"
            ],
            "formatString": "0",
            "lineageTag": "184f8173-81d1-41bd-aca9-eaa92d4f16de"
          },
          {
            "name": "URPFA LB",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "Var _Top = TopN(20, ADDCOLUMNS(VALUES('Dim Employee'[Employee Key]), \"_Amt\", [Proforma Amt After Date]), ",
              "[_Amt], DESC )",
              "VAR _Result = Sumx(_Top, [_Amt])",
              "RETURN _Result"
            ],
            "lineageTag": "5ed6f9a1-c48a-43e4-ae7f-019bb840be42"
          },
          {
            "name": "Leaderboard URPF Amt Atty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              " CALCULATE([Proforma Amt After Date], 'Dim Role Type'[Role Type Description] = \"Billing Attorney\", 'Dim Employee'[Employee Active] = \"Active\",'Dim Matter'[Arrangement Code] <> \"C\", 'Dim Proforma'[Proforma Billing Status Code] <> \"Billed\", 'Dim Proforma'[Proforma Responsible Party Description] = \"ATTORNEY\")"
            ],
            "lineageTag": "12a2c341-fa4b-40e4-85a7-22632e411e88"
          },
          {
            "name": "Leaderboard URPF Number Atty",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              " CALCULATE([Proforma Count After Date], 'Dim Role Type'[Role Type Description] = \"Billing Coordinator\", 'Dim Employee'[Employee Active] = \"Active\",'Dim Matter'[Arrangement Code] <> \"C\", 'Dim Proforma'[Proforma Billing Status Code] <> \"Billed\", 'Dim Proforma'[Proforma Responsible Party Description] = \"ATTORNEY\")"
            ],
            "formatString": "0",
            "lineageTag": "a444d772-d714-4f35-b217-8def982fe51c"
          },
          {
            "name": "RANK Employee URPFA Biller",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Amt Acct],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Amt Acct],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "029a389b-c55c-450b-b8b2-1105478005af"
          },
          {
            "name": "Leaderboard URPF Amt Acct",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              " CALCULATE([Proforma Amt After Date], 'Dim Role Type'[Role Type Description] = \"Billing Attorney\", 'Dim Employee'[Employee Active] = \"Active\",'Dim Matter'[Arrangement Code] <> \"C\", 'Dim Proforma'[Proforma Billing Status Code] <> \"Billed\", 'Dim Proforma'[Proforma Responsible Party Description] = \"ATTORNEY\")"
            ],
            "lineageTag": "7ed82ab2-4aee-4f75-98b7-689b11e02082"
          },
          {
            "name": "RANK Employee URPFN Biller",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "Var _RnkTop = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Number Acct],,DESC,Dense)",
              "Var _RnkBottom = RANKX(ALLSELECTED('Dim Employee'[Employee Key]), [Leaderboard URPF Number Acct],,ASC,Dense)",
              "Var _Sel = SELECTEDVALUE('Leaderboard Selection'[Leaderboard Selection])",
              "VAR _Rnk = if(_Sel = \"Top 20\", _RnkTop, _RnkBottom)",
              "RETURN _Rnk"
            ],
            "formatString": "0",
            "lineageTag": "3ee5d65f-7766-4c69-888d-4f3b2b59aa81"
          },
          {
            "name": "Leaderboard URPF Number Acct",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              " CALCULATE([Proforma Count After Date], 'Dim Role Type'[Role Type Description] = \"Billing Coordinator\", 'Dim Employee'[Employee Active] = \"Active\",'Dim Matter'[Arrangement Code] <> \"C\", 'Dim Proforma'[Proforma Billing Status Code] <> \"Billed\", 'Dim Proforma'[Proforma Responsible Party Description] = \"ACCOUNTING\")"
            ],
            "formatString": "0",
            "lineageTag": "f095524e-318f-41ae-9937-22dd41602cad"
          },
          {
            "name": "Leaderboard Biller",
            "displayFolder": "Leaderboard",
            "expression": [
              "",
              "var _Name = Min('Dim Employee'[Employee Display Name])",
              " var _PGname = Calculate(Min('Dim Practice Group'[Practice Group Short Description]), 'Fact AR Snapshot')",
              " var _PG = if(len(_PGname)>25, left(_PGname,25) & \"...\", _PGname)",
              "  var _Pgc = Calculate(Min('Dim Practice Group'[Practice Group Code]), 'Fact AR Snapshot')",
              " var _ext = \"x\" & Format(Min('Dim Employee'[Phone Bus Ext Number]), \"#\")",
              " var _result = TRIM(_Name  & \", \" & _ext & Unichar(10) & _PG & \" (\" & _Pgc & \")\" )",
              " return _result "
            ],
            "lineageTag": "f80bfe47-116d-44d4-b08b-bbd2ee233499"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": "{BLANK()}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Number Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ca498f6-620e-4318-bc5a-57533c7a939f",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bd1780b5-728e-4d92-bc8f-2fc8fd8adfad",
        "partitions": [
          {
            "name": "Number Type",
            "mode": "import",
            "queryGroup": "PBI Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcipNSU8tUYrViVZyLi0qSs2DsAOK8rNSk0tSU6C8zPwihcjUxCKl2FgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Type\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Trend Arrows",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ceb0041-4ff1-45b8-b1df-285a86822522",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "93152f36-eeba-488c-9a08-476a977bdc8d",
            "sourceColumn": "Image",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f54cddfb-824a-4b8c-9bc7-dbe721a8c54d",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc54f3d0-2208-476d-82a4-beae16abfb2e",
        "measures": [
          {
            "name": "Selected Image",
            "dataCategory": "ImageUrl",
            "expression": "Min('Trend Arrows'[Image])",
            "lineageTag": "a76e579f-132f-4f04-b91a-4be5efecfb03"
          }
        ],
        "partitions": [
          {
            "name": "Trend Arrows",
            "mode": "import",
            "queryGroup": "PBI Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"7L3XkuNI0ib6Lv8t1gxanWN7ARAktCA0sXYuIElCa/X0B8zqUl1VPVUtpmd7isa0\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, Image = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Name\", type text}, {\"Image\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Name\", \"Image\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Office",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currenct Record",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c5bd1c98-55be-4335-88c6-94b6355501a0",
            "sourceColumn": "Currenct Record",
            "summarizeBy": "none"
          },
          {
            "name": "Telework Office",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c2cc2f8-9e91-4b33-9964-4e3d4999e4ba",
            "sourceColumn": "Telework Office",
            "summarizeBy": "none"
          },
          {
            "name": "Headquarters",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8522df4e-ed00-414a-acdd-ffd6f7377298",
            "sourceColumn": "Headquarters",
            "summarizeBy": "none"
          },
          {
            "name": "Office Active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8251033a-0c96-4829-bf61-5ce66fb6a7ec",
            "sourceColumn": "Office Active",
            "summarizeBy": "none"
          },
          {
            "name": "Office Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96fe9160-8101-48db-8844-ed51b97a58f4",
            "sourceColumn": "Office Group",
            "summarizeBy": "none"
          },
          {
            "name": "Regulatory Region Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87356127-b4f6-4631-b406-7f56351a4708",
            "sourceColumn": "Regulatory Region Description",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85a788e2-45bd-46cc-bd32-009d819b1444",
            "sourceColumn": "Phone Number",
            "summarizeBy": "none"
          },
          {
            "name": "Country Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "966ee1df-5f63-439b-9238-5d90be1f4ae2",
            "sourceColumn": "Country Code",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "747a9c1a-b8c9-4814-a35c-2c8f9b5d147d",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "State Province Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "770378d3-a6f0-467a-bc39-aa2be2bd526e",
            "sourceColumn": "State Province Code",
            "summarizeBy": "none"
          },
          {
            "name": "City Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c50fd672-85cf-4c4c-9a86-d657a67a687a",
            "sourceColumn": "City Text",
            "summarizeBy": "none"
          },
          {
            "name": "Office Short Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8a45505-ed84-46b0-ad03-f767860d6d40",
            "sourceColumn": "Office Short Description",
            "summarizeBy": "none"
          },
          {
            "name": "Office Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd8d297a-8a36-4da8-8c32-f1b39b9605f4",
            "sourceColumn": "Office Description",
            "summarizeBy": "none"
          },
          {
            "name": "Office Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c15f858a-8b98-4ce2-9579-97dc077f19a8",
            "sourceColumn": "Office Code",
            "summarizeBy": "none"
          },
          {
            "name": "HR Office ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "956a8411-7a2c-4132-bc9c-4b7dfc2bf982",
            "sourceColumn": "HR Office ID",
            "summarizeBy": "count"
          },
          {
            "name": "Finance Office ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a980283a-fe52-40d6-9213-3429baefa4fc",
            "sourceColumn": "Finance Office ID",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81c605ca-b997-4b53-aa64-d69968288780",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a836d8a4-2b4e-41c7-bf28-bfc8bbbf2efd",
            "sourceColumn": "Office Display Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "74834461-2611-4cbe-a126-f069b0101c9a",
        "partitions": [
          {
            "name": "Dim Office",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_office_Table = main_Schema{[Name=\"dim_office\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_office_Table,{\"OfficeKey\", \"FinanceOfficeID\", \"HROfficeID\", \"OfficeCode\", \"OfficeDescription\", \"OfficeShortDescription\", \"CityText\", \"StateProvinceCode\", \"PostalCode\", \"CountryCode\", \"PhoneNumber\", \"RegulatoryRegionDescription\", \"OfficeGroup\", \"isOfficeActive\", \"isHeadquarters\", \"isTeleworkOffice\", \"isCurrenctRecord\", \"OfficeDisplayName\"})",
                ",",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{ {\"Finance Office I D\", \"Finance Office ID\"}, {\"H R Office I D\", \"HR Office ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Practice Group",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f74a22a-b16d-4453-b2cf-e88dcfa8914a",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c880279a-da03-4f62-94a0-94d21a021f36",
            "sourceColumn": "Practice Group ID",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68de0fda-90a8-4739-a3da-0d1a579e4c95",
            "sourceColumn": "Practice Group Description",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Short Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52bd849f-06d7-4303-a09f-ccb2454ed7ad",
            "sourceColumn": "Practice Group Short Description",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d18dc75b-48c2-437e-a126-59ea182d7257",
            "sourceColumn": "Practice Group Active",
            "summarizeBy": "none"
          },
          {
            "name": "Current Record",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "21989de1-cec3-4fca-97c4-1544ba4635e0",
            "sourceColumn": "Current Record",
            "summarizeBy": "none"
          },
          {
            "name": "Department Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d554ef0-4e00-40e3-b1b7-ac21cb1fc384",
            "sourceColumn": "Department Description",
            "summarizeBy": "none"
          },
          {
            "name": "Department ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8d43a75-6ccd-40f0-9f2a-fda5d595a06f",
            "sourceColumn": "Department ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department Short Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1db31bc0-86bc-403e-a2cc-397eab966d67",
            "sourceColumn": "Department Short Description",
            "summarizeBy": "none"
          },
          {
            "name": "Department Type Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7612d87-1f30-4b4a-930b-a3e9baf472c2",
            "sourceColumn": "Department Type Text",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de8613b6-42ee-4802-9e1a-153e693424f3",
            "sourceColumn": "Practice Group Code",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "196c47f8-05fd-47a9-999b-31396585da78",
            "sourceColumn": "Practice Group Display Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ae2acb54-42a2-499e-82b5-f3a587aed0c5",
        "partitions": [
          {
            "name": "Dim Practice Group",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_practicegroup_Table = main_Schema{[Name=\"dim_practicegroup\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_practicegroup_Table,{\"PracticeGroupKey\", \"DepartmentDescription\", \"DepartmentID\", \"PracticeGroupID\", \"DepartmentShortDescription\", \"DepartmentTypeText\", \"PracticeGroupDescription\", \"PracticeGroupShortDescription\", \"isPracticeGroupActive\", \"isCurrentRecord\", \"PracticeGroupCode\", \"PracticeGroupDisplayName\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Practice Group I D\", \"Practice Group ID\"},  {\"Department I D\", \"Department ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ead2c723-d396-45e9-ac8e-333eb6e0c61a",
            "sourceColumn": "Currency Key",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94901757-3056-4524-88db-d9616c203445",
            "sourceColumn": "Currency Code",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b832d63c-27d7-4547-8e33-896b5454f0e3",
            "sourceColumn": "Currency Name",
            "summarizeBy": "none"
          },
          {
            "name": "Format String",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70aaaa31-5c80-4005-b995-b35e7599c0ea",
            "sourceColumn": "Format String",
            "summarizeBy": "none"
          },
          {
            "name": "Leading Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a373ac13-3cdc-4615-8af3-73873267acd0",
            "sourceColumn": "Leading Text",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "94b44764-5149-4eab-b0f1-aee4a725a766",
        "partitions": [
          {
            "name": "Dim Currency",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_currency_Table = main_Schema{[Name=\"dim_currency\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_currency_Table,{\"CurrencyKey\", \"CurrencyCode\", \"CurrencyName\", \"FormatString\", \"LeadingText\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact WIP Snapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "789093d8-e924-4466-9ac0-b331fb1d5882",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dadbb6e1-2325-4dc0-810f-d2c3945a3468",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d55eae67-9a70-43f0-9a70-45dec6ef2749",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e74c6548-0917-4da0-988c-de4a53110767",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "As of Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6a978619-54b4-4b72-bc01-19126ef97e56",
            "sourceColumn": "As of Date",
            "summarizeBy": "none"
          },
          {
            "name": "WIP Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e7436d3-c8c1-45e0-8e73-d6bacbe21930",
            "sourceColumn": "WIP Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Matter Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3ef2ad4-e3c2-43a5-85b6-673dc60f3432",
            "sourceColumn": "Matter Currency Key",
            "summarizeBy": "count"
          },
          {
            "name": "Firm Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b69a1e4-68d9-44b5-89a8-79d021fd0c8d",
            "sourceColumn": "Firm Currency Key",
            "summarizeBy": "count"
          },
          {
            "name": "Office Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe8b32a7-d62d-4d97-bbad-cd4acb46e37a",
            "sourceColumn": "Office Currency Key",
            "summarizeBy": "count"
          },
          {
            "name": "Client Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7dee8d6c-2879-4f1a-bf5e-b70c4b016391",
            "sourceColumn": "Client Currency Key",
            "summarizeBy": "count"
          },
          {
            "name": "Proforma Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "de337106-cfd4-4d46-913d-3afdcd61fffa",
            "sourceColumn": "Proforma Key",
            "summarizeBy": "count"
          },
          {
            "name": "WIP Age Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f49232d7-ec64-4e2b-b7ba-eb49b3a19cb4",
            "sourceColumn": "WIP Age Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Aging Buckets Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bdb1782f-9f7a-4382-8b5f-2a08ba87c642",
            "sourceColumn": "Aging Buckets Key",
            "summarizeBy": "none"
          },
          {
            "name": "Fees To Bill Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f4973de-333d-4f35-8750-0215ad960594",
            "sourceColumn": "Fees To Bill Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Fees To Bill Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "48ee58b5-6423-47bc-b383-0d6566e23ccb",
            "sourceColumn": "Fees To Bill Relieved Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "W I P Fees Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4bf604d7-6402-4ee5-b8bc-da8bad74efee",
            "sourceColumn": "W I P Fees Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37a9011f-539c-4ede-859d-7a04fbd767cc",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "count"
          },
          {
            "name": "Disbursed To Bill Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef585bfd-8b67-498b-89be-04c247922a46",
            "sourceColumn": "Disbursed To Bill Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Disbursed To Bill Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "866915b1-b5f5-4928-8ed8-0a091e701e15",
            "sourceColumn": "Disbursed To Bill Relieved Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Hours To Bill Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a80e135b-6c53-440a-a50a-fd81d28da7b9",
            "sourceColumn": "Hours To Bill Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Hours To Bill Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3d0f26ba-da1a-43e4-8ff4-64b412ad826c",
            "sourceColumn": "Hours To Bill Relieved Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "W I P Hours Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0ac3c067-7aee-4410-8281-2e92ecb1a537",
            "sourceColumn": "W I P Hours Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Disbursed Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "33cfc9de-76af-4a77-b54f-f6dd50be8b6e",
            "sourceColumn": "Total Disbursed Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Soft Disbursed Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aaa14505-54cd-4659-b0a8-cdc952b5a63b",
            "sourceColumn": "Soft Disbursed Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Hard Disbursed Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "eacd4c73-cadd-4634-836b-9ac6d20c38b5",
            "sourceColumn": "Hard Disbursed Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Fee Write Up Write Down Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "227e1f6c-675c-4fb8-86fd-ecfab63f4995",
            "sourceColumn": "Fee Write Up Write Down Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Standard Fees Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e37f9894-48e1-4ffe-b37a-74eea6b3c5f4",
            "sourceColumn": "Standard Fees Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Fees Relieved Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "40c81a68-c17d-4dd0-a0bf-d44bac430782",
            "sourceColumn": "Fees Relieved Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Fees Discount Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f43796bf-5f77-43dd-a95f-d712259ce77d",
            "sourceColumn": "Total Fees Discount Amount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "647e35db-5582-4054-94a0-5de768fee8ba",
        "partitions": [
          {
            "name": "Fact WIP Snapshot",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    DateLimit = Date.AddYears(Date.From(DateTime.LocalNow()),-2),",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_wipsnapshot_Table = main_Schema{[Name=\"fact_wipsnapshot\",Kind=\"Table\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(fact_wipsnapshot_Table, each [AsofDate] > DateLimit),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"ClientKey\", \"MatterKey\", \"OfficeKey\", \"PracticeGroupKey\", \"InvoiceKey\", \"ProformaKey\", \"AgingBucketsKey\", \"AsofDate\", \"DisbursedToBillAmount\", \"DisbursedToBillRelievedAmount\", \"FeesToBillAmount\", \"FeesToBillRelievedAmount\", \"HoursToBillAmount\", \"HoursToBillRelievedAmount\", \"WIPHoursAmount\", \"WIPFeesAmount\", \"WIPAmount\", \"TotalDisbursedWriteDownAmount\", \"SoftDisbursedWriteDownAmount\", \"HardDisbursedWriteDownAmount\", \"FeeWriteUpWriteDownAmount\", \"StandardFeesAmount\", \"FeesRelievedAmount\", \"TotalFeesDiscountAmount\", \"WIPAgeDays\", \"MatterCurrencyKey\", \"FirmCurrencyKey\", \"OfficeCurrencyKey\", \"ClientCurrencyKey\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Asof Date\", \"As of Date\"}, {\"W I P Amount\", \"WIP Amount\"}, {\"W I P Age Days\", \"WIP Age Days\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Aging Buckets",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Aging Buckets Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08c99039-c0c6-44d1-897b-fd5b0d4a4b2d",
            "sourceColumn": "Aging Buckets Key",
            "summarizeBy": "none"
          },
          {
            "name": "Aging Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15522d19-43d8-4c11-84c4-161440da9bc2",
            "sourceColumn": "Aging Code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "62e5a238-5a5a-4f24-9a79-b4649a1ecfe7",
        "partitions": [
          {
            "name": "Dim Aging Buckets",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_agingbuckets_Table = main_Schema{[Name=\"dim_agingbuckets\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_agingbuckets_Table,{\"AgingBucketsKey\", \"AgingCode\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Receipts",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Receipts Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af86005c-6a05-4c90-9dc0-93a50476d98b",
            "sourceColumn": "Receipts Key",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "392a8936-9ca6-497a-809d-e1a34b240425",
            "sourceColumn": "Receipt ID",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8029032e-7d4f-44c3-8821-21b3c7a03d0a",
            "sourceColumn": "Receipt Text",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt Type Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91fae077-a693-4007-be00-30c6e84ce0a1",
            "sourceColumn": "Receipt Type Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bbc55eb5-0042-478d-83b3-caf65efbdce4",
        "partitions": [
          {
            "name": "Dim Receipts",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_receipts_Table = main_Schema{[Name=\"dim_receipts\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_receipts_Table,{\"ReceiptsKey\", \"ReceiptID\", \"ReceiptText\", \"ReceiptTypeDescription\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Receipt I D\", \"Receipt ID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Firm Target",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Firm Target Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9be38ff7-3c09-4aac-afe6-29f92a1d7652",
            "sourceColumn": "Firm Target Key",
            "summarizeBy": "none"
          },
          {
            "name": "Target Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c242675-534d-463b-a150-cb0362ae42cf",
            "sourceColumn": "Target Type",
            "summarizeBy": "none"
          },
          {
            "name": "Target Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "146e7f15-dd2f-41bc-a974-be1fabca9610",
            "sourceColumn": "Target Description",
            "summarizeBy": "none"
          },
          {
            "name": "Target Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a78ab9d7-6644-4686-91f9-5a557e40be3a",
            "sourceColumn": "Target Period",
            "summarizeBy": "none"
          },
          {
            "name": "Target Direction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "453108df-d984-4006-8b09-c64c141ed16c",
            "sourceColumn": "Target Direction",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a0944d65-fcf9-4b05-8e11-abcfcb9cfa27",
            "sourceColumn": "Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "908ac2f1-c30d-4139-997f-163b49288d9e",
            "sourceColumn": "End Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "df5ffc05-6868-4377-9b99-6f38861c7fba",
        "partitions": [
          {
            "name": "Dim Firm Target",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    dim_firmtarget_Table = main_Schema{[Name=\"dim_firmtarget\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dim_firmtarget_Table,{\"FirmTargetKey\", \"TargetType\", \"TargetDescription\", \"TargetPeriod\", \"TargetDirection\", \"StartDate\", \"EndDate\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Employment By Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "As of Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f6905428-bcf9-4fb3-b566-b404dd50b8fc",
            "sourceColumn": "As of Date",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4cbe93e9-dcbd-4534-9ba0-669a75640644",
            "sourceColumn": "Employee Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "030859de-4698-4679-a182-b2540d22a31d",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e51a1430-e45d-4965-962a-cf297c4ded83",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Hours Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a13f6429-c081-4f2f-bc56-54930db18143",
            "sourceColumn": "Budgeted Hours Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Standard Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fe9fa5a9-0938-4f3d-a401-4d684c52f85a",
            "sourceColumn": "Effective Standard Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Budgeted Fees Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "47f6c6c7-c466-4edb-809a-f7bc1d8203f3",
            "sourceColumn": "Budgeted Fees Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Holiday Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "088291d8-94be-4b41-8d3d-eb0da6fc92f1",
            "sourceColumn": "Is Holiday Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Is Workday Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "04522814-5db6-49cd-8c4a-30ff6c5b6e1c",
            "sourceColumn": "Is Workday Flag",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a8204097-298d-4052-a229-b1eb2d58e23a",
        "partitions": [
          {
            "name": "Fact Employment By Date",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    DateLimit = Date.AddYears(Date.From(DateTime.LocalNow()),-2),",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_employmentbydate_Table = main_Schema{[Name=\"fact_employmentbydate\",Kind=\"Table\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(fact_employmentbydate_Table, each [AsofDate] > DateLimit),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"AsofDate\", \"EmployeeKey\", \"PracticeGroupKey\", \"OfficeKey\", \"BudgetedHoursAmount\", \"EffectiveStandardRate\", \"BudgetedFeesAmount\", \"IsHolidayFlag\", \"IsWorkdayFlag\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Asof Date\", \"As of Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact AR Snapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "12c1cc60-2510-4aea-b732-72db7b7ebb91",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4a59f71-674a-4b21-86f8-8e649937fa38",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46507490-9699-4d5f-aeae-07dd0d486049",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "count"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92a275b7-216e-473c-9226-51f229e9395a",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28083913-99da-4be9-a6fb-2fb03e7c96cd",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Aging Buckets Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4af57531-7146-4235-819b-06fb892d8b86",
            "sourceColumn": "Aging Buckets Key",
            "summarizeBy": "none"
          },
          {
            "name": "As of Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1d921a84-407d-4efa-ade9-7c209318ac6b",
            "sourceColumn": "As of Date",
            "summarizeBy": "none"
          },
          {
            "name": "AR Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "732e6805-793c-4b9a-b2db-2c5fee9c2ed8",
            "sourceColumn": "AR Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "AR Age Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ce0ff9d-52e7-413e-b808-003a32f2c2f8",
            "sourceColumn": "AR Age Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Weighted AR Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "60e1a338-2f7a-4b54-9c53-51d5dec8b7a2",
            "sourceColumn": "Weighted AR Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Weighted AR Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "412accfd-3948-47f4-a462-eb6f9bde02c5",
            "sourceColumn": "Weighted AR Days",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b2584942-e076-4c4b-b596-233bf9d71db5",
        "partitions": [
          {
            "name": "Fact AR Snapshot",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    DateLimit = Date.AddYears(Date.From(DateTime.LocalNow()),-2),",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_arsnapshot_Table = main_Schema{[Name=\"fact_arsnapshot\",Kind=\"Table\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(fact_arsnapshot_Table, each [AsofDate] > DateLimit),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"ClientKey\", \"MatterKey\", \"InvoiceKey\", \"PracticeGroupKey\", \"OfficeKey\", \"AgingBucketsKey\", \"AsofDate\", \"ARAmount\", \"ARAgeDays\", \"WeightedARAmount\", \"WeightedARDays\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add Spaces\",{{\"Asof Date\", \"As of Date\"}, {\"A R Amount\", \"AR Amount\"}, {\"A R Age Days\", \"AR Age Days\"}, {\"Weighted A R Amount\", \"Weighted AR Amount\"}, {\"Weighted A R Days\", \"Weighted AR Days\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Firm Target Snapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Target Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5da6431b-fa5c-40fc-8cd0-153f2b2410ea",
            "sourceColumn": "Target Date",
            "summarizeBy": "none"
          },
          {
            "name": "Firm Target Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97f93af6-057d-4784-b526-582314ad8194",
            "sourceColumn": "Firm Target Key",
            "summarizeBy": "none"
          },
          {
            "name": "Target Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30833fc9-8351-4f63-acf9-1e5d40212ca5",
            "sourceColumn": "Target Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Target Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0129bbe-ba85-45d0-a4ee-d2f6404ffde3",
            "sourceColumn": "Target Currency Key",
            "summarizeBy": "none"
          },
          {
            "name": "Firm Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "685617d7-835d-40e2-bd13-f0d31f9c66f0",
            "sourceColumn": "Firm Currency Key",
            "summarizeBy": "count"
          },
          {
            "name": "Office Currency Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "504544d9-e4c9-45eb-846e-1b39224d6c1e",
            "sourceColumn": "Office Currency Key",
            "summarizeBy": "count"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e07de4df-34b1-4c08-ac12-4df54e13fa5d",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6022078-c87d-48be-b9cc-cc3049b320f9",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee077042-c3b9-49ef-a95b-858d9e9fcb28",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "465834b1-e281-4451-9133-b3acf04444f1",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7256c177-f778-452c-ae22-d581dcbca144",
        "partitions": [
          {
            "name": "Fact Firm Target Snapshot",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_firmtargetsnapshot_Table = main_Schema{[Name=\"fact_firmtargetsnapshot\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fact_firmtargetsnapshot_Table,{\"TargetDate\", \"FirmTargetKey\", \"TargetAmount\", \"TargetCurrencyKey\", \"FirmCurrencyKey\", \"OfficeCurrencyKey\", \"ClientKey\", \"MatterKey\", \"OfficeKey\", \"PracticeGroupKey\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Receipt Transactions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Receipts Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e1b7fc98-7892-4362-9388-e91a5dcc0401",
            "sourceColumn": "Receipts Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "624def03-2c68-4e6a-821f-db09d778f28f",
            "sourceColumn": "Client Key",
            "summarizeBy": "none"
          },
          {
            "name": "Matter Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dfed0f65-bab3-481e-896d-ff7284cedd47",
            "sourceColumn": "Matter Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97d04d1e-daac-4871-821d-031ba9f2b611",
            "sourceColumn": "Invoice Key",
            "summarizeBy": "count"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8110430-2bf5-4f48-8589-22175131e701",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95022db4-d292-4fa6-845f-50101be0ee64",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "546a6737-ae65-4934-94d6-224baed06194",
            "sourceColumn": "Receipt Date",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt Total Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4b0bcebf-c146-42c8-b3c6-49492ee59c78",
            "sourceColumn": "Receipt Total Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Receipt Fee Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "95369926-ac3f-4656-9e97-f95942c97923",
            "sourceColumn": "Receipt Fee Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Receipt Hard Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5edbbb09-6ebb-4555-b094-cc10bedd9feb",
            "sourceColumn": "Receipt Hard Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Receipt Soft Cost Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ea73cea-734b-4668-bd0c-82bfe0e1e130",
            "sourceColumn": "Receipt Soft Cost Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Receipt Other Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2fa2fa52-5707-4034-8d8e-c673204fd1af",
            "sourceColumn": "Receipt Other Amount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6e81b382-3625-47ae-88b4-cadfbc341e1e",
        "partitions": [
          {
            "name": "Fact Receipt Transactions",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_receipttransactions_Table = main_Schema{[Name=\"fact_receipttransactions\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fact_receipttransactions_Table,{\"ReceiptsKey\", \"ClientKey\", \"MatterKey\", \"InvoiceKey\", \"PracticeGroupKey\", \"OfficeKey\", \"ReceiptDate\", \"ReceiptTotalAmount\", \"ReceiptFeeAmount\", \"ReceiptHardCostAmount\", \"ReceiptSoftCostAmount\", \"ReceiptOtherAmount\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Reporting Preferences",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Field Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2d38bf0-c394-478e-9dab-d980d0b8a081",
            "sourceColumn": "Field Key",
            "summarizeBy": "count"
          },
          {
            "name": "Field Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4b779fce-2534-4b7c-ae73-7327535149cf",
            "sourceColumn": "Field Description",
            "summarizeBy": "none"
          },
          {
            "name": "Field Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a6a09367-692c-49b3-bf5a-08896383bac9",
            "sourceColumn": "Field Value",
            "summarizeBy": "none"
          },
          {
            "name": "Field Last Updated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "1bddba9b-ad7e-4d8a-ab65-d1bfb6d7beed",
            "sourceColumn": "Field Last Updated",
            "summarizeBy": "none"
          },
          {
            "name": "Field Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5d19c8b4-13d9-494e-8c7d-5901404d2c3c",
            "sourceColumn": "Field Category",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "f8fe3f03-3a35-44fd-98cf-b6bfc59d227a",
        "partitions": [
          {
            "name": "Reporting Preferences",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    custom_reportingpreferences_Table = main_Schema{[Name=\"custom_reportingpreferences\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(custom_reportingpreferences_Table,{\"FieldKey\", \"FieldDescription\", \"FieldValue\", \"FieldLastUpdated\", \"FieldCategory\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Employee Photo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5221ea02-643d-4a87-ad9d-0bdee2887cd5",
            "sourceColumn": "Employee Key",
            "summarizeBy": "none"
          },
          {
            "name": "Image File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "665201e5-f914-4d5a-a70b-e252aaa22318",
            "sourceColumn": "Image File Name",
            "summarizeBy": "none"
          },
          {
            "name": "Base64 Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bd83586-4bcb-4c34-90aa-eab175833f51",
            "sourceColumn": "Base64 Text",
            "summarizeBy": "none"
          },
          {
            "name": "Sequence Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a40c4dd9-2e91-47dc-becf-e35cf3c97367",
            "sourceColumn": "Sequence Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5c559c65-da74-4b25-b901-c8ed88acd32a",
        "partitions": [
          {
            "name": "Fact Employee Photo",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "     gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_employeephotos_Table = main_Schema{[Name=\"fact_employeephotos\",Kind=\"Table\"]}[Data],",
                "     #\"Removed Other Columns\" = Table.SelectColumns(fact_employeephotos_Table,{\"EmployeeKey\", \"ImageFileName\", \"Base64Text\", \"SequenceNumber\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Employee Snapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c1b2aef-fb01-4d68-adda-b1a7a461b8f2",
            "sourceColumn": "Employee Key",
            "summarizeBy": "none"
          },
          {
            "name": "Practice Group Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "884247c7-703d-426e-a4e7-051f3de5b8c2",
            "sourceColumn": "Practice Group Key",
            "summarizeBy": "none"
          },
          {
            "name": "Office Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d7e348b-9149-4fc6-a599-37303227ea0c",
            "sourceColumn": "Office Key",
            "summarizeBy": "none"
          },
          {
            "name": "Performance Year End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9de65e1-5e9b-414e-9dc4-27899f4e6aaf",
            "sourceColumn": "Performance Year End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Employment Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e47e288e-88b0-4d7f-bb9e-93fc2231442b",
            "sourceColumn": "Employment Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Employment End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "64c95ea8-cacb-4353-b34a-c1c43339f557",
            "sourceColumn": "Employment End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Employment Recent Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "90ba64e5-10ed-4643-87ed-ff7eb15d5168",
            "sourceColumn": "Employment Recent Hire Date",
            "summarizeBy": "none"
          },
          {
            "name": "Hours Billable Annual Target Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0aa995f3-ea1e-480d-b123-589826090fa4",
            "sourceColumn": "Hours Billable Annual Target Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c61b019d-95a3-4117-9582-81287b79e010",
        "partitions": [
          {
            "name": "Fact Employee Snapshot",
            "mode": "import",
            "queryGroup": "Databricks Tables",
            "source": {
              "expression": [
                "let",
                "    DateLimit = Date.AddYears(Date.From(DateTime.LocalNow()),-2),",
                "    Source = Databricks.Catalogs(DatabricksHost, DatabricksHTTPPath, [Catalog = \"\", Database = \"\"]),",
                "    gold_Database = Source{[Name=Catalog,Kind=\"Database\"]}[Data],",
                "    main_Schema = gold_Database{[Name=\"main\",Kind=\"Schema\"]}[Data],",
                "    fact_employeesnapshot_Table = main_Schema{[Name=\"fact_employeesnapshot\",Kind=\"Table\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fact_employeesnapshot_Table,{\"EmployeeKey\", \"PracticeGroupKey\", \"OfficeKey\", \"PerformanceYearEndDate\", \"EmploymentStartDate\", \"EmploymentEndDate\", \"EmploymentRecentHireDate\", \"HoursBillableAnnualTargetNumber\"}),",
                "    #\"Add Spaces\" = Table.TransformColumnNames(#\"Removed Other Columns\", each Text.Combine(Splitter.SplitTextByPositions(Text.PositionOfAny(_, {\"A\"..\"Z\"},2)) (_), \" \"))",
                "in",
                "    #\"Add Spaces\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Leaderboard Selection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Leaderboard Selection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "32f25b35-5dd7-4446-b966-18d7efba4cea",
            "sortByColumn": "Sort Order",
            "sourceColumn": "Leaderboard Selection",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d18728a-ca14-493c-890b-183588b91f9e",
            "sourceColumn": "Sort Order",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6e586526-1a6e-4aab-95fb-42a57ba9e635",
        "partitions": [
          {
            "name": "Leaderboard Selection",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCskvUDAyUIrViVZyyi8pyc8F82IB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Leaderboard Selection\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Leaderboard Selection\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 0, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Sort Order\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}